const fs = require('fs');

// Top 515+ US Companies (S&P 500 & NASDAQ 100 & Russell 1000 Leaders)
const usStocksRaw = [
  // Mega-Cap Tech & Magnificent 7
  ['NVDA', 'NVIDIA Corporation', 'Yarı İletken & AI Hızlandırıcılar', 142.50],
  ['AAPL', 'Apple Inc.', 'Tüketici Elektroniği & Ekosistem', 242.00],
  ['MSFT', 'Microsoft Corporation', 'Bulut & Kurumsal Yazılım / AI', 448.00],
  ['AMZN', 'Amazon.com Inc.', 'E-Ticaret & AWS Bulut Bilişim', 214.00],
  ['GOOGL', 'Alphabet Inc. (Class A)', 'Arama, Dijital Reklam & AI', 188.00],
  ['GOOG', 'Alphabet Inc. (Class C)', 'Arama, Dijital Reklam & AI', 189.50],
  ['META', 'Meta Platforms Inc.', 'Sosyal Medya & Yapay Zeka', 594.00],
  ['TSLA', 'Tesla Inc.', 'Elektrikli Araç & Otonom Sürüş', 345.00],
  ['BRK-B', 'Berkshire Hathaway Inc.', 'Finansal Holding & Sigorta', 472.00],
  ['LLY', 'Eli Lilly and Company', 'İlaç & Biyoteknoloji / GLP-1', 785.00],
  ['AVGO', 'Broadcom Inc.', 'Özel AI Çipleri & Ağ Donanımı', 168.00],
  ['JPM', 'JPMorgan Chase & Co.', 'Yatırım & Ticari Bankacılık', 248.00],
  ['V', 'Visa Inc.', 'Küresel Dijital Ödeme Ağı', 315.00],
  ['UNH', 'UnitedHealth Group Inc.', 'Sağlık Sigortası & Hizmetleri', 595.00],
  ['XOM', 'Exxon Mobil Corporation', 'Entegre Petrol & Doğalgaz', 118.00],
  ['MA', 'Mastercard Incorporated', 'Ödeme Sistemleri & Fintek', 525.00],
  ['COST', 'Costco Wholesale Corp.', 'Toptan & Üyelikli Perakende', 945.00],
  ['PG', 'Procter & Gamble Co.', 'Tüketici Ürünleri & Temizlik', 174.00],
  ['HD', 'The Home Depot Inc.', 'Ev Geliştirme & Yapı Perakende', 412.00],
  ['JNJ', 'Johnson & Johnson', 'İlaç & Medikal Cihazlar', 158.00],
  ['NFLX', 'Netflix Inc.', 'Dijital Yayın & Medya Eğlence', 890.00],
  ['ABBV', 'AbbVie Inc.', 'Biyofarmasötik & İmmünoloji', 178.00],
  ['WMT', 'Walmart Inc.', 'Perakende & Süpermarketler', 88.00],
  ['CRM', 'Salesforce Inc.', 'Bulut Tabanlı CRM & Ajanlar', 335.00],
  ['BAC', 'Bank of America Corp.', 'Bankacılık & Finansal Hizmetler', 46.50],
  ['KO', 'The Coca-Cola Company', 'Alkolsüz İçecek & Meşrubat', 64.50],
  ['ORCL', 'Oracle Corporation', 'Veritabanı & Bulut Altyapısı', 192.00],
  ['CVX', 'Chevron Corporation', 'Entegre Enerji & Akaryakıt', 158.00],
  ['MRK', 'Merck & Co. Inc.', 'Onkoloji & İlaç Geliştirme', 104.00],
  ['AMD', 'Advanced Micro Devices', 'Yarı İletken & Veri Merkezi Çipleri', 138.00],
  ['PEP', 'PepsiCo Inc.', 'İçecek & Atıştırmalık Gıda', 162.00],
  ['TMO', 'Thermo Fisher Scientific', 'Analitik Cihazlar & Laboratuvar', 525.00],
  ['LIN', 'Linde plc', 'Endüstriyel Gazlar & Kimya', 455.00],
  ['ACN', 'Accenture plc', 'BT Danışmanlığı & Dijital Dönüşüm', 365.00],
  ['ADBE', 'Adobe Inc.', 'Yaratıcı Yazılım & Üretken AI', 510.00],
  ['MCD', 'McDonald\'s Corporation', 'Hızlı Servis Restoran Zinciri', 295.00],
  ['QCOM', 'Qualcomm Inc.', 'Mobil Yonga & 5G İletişim', 165.00],
  ['CSCO', 'Cisco Systems Inc.', 'Ağ Donanımı & Kurumsal Güvenlik', 58.00],
  ['DIS', 'The Walt Disney Company', 'Medya, Eğlence & Tema Parkları', 114.00],
  ['IBM', 'International Business Machines', 'Hibrit Bulut & Kurumsal AI', 228.00],
  ['GE', 'GE Aerospace', 'Havacılık Motorları & Sistemleri', 188.00],
  ['TXN', 'Texas Instruments Inc.', 'Analog Yarı İletkenler', 215.00],
  ['CAT', 'Caterpillar Inc.', 'İş Makineleri & Ağır Ekipman', 395.00],
  ['PM', 'Philip Morris International', 'Tütün & Dumansız Alternatifler', 132.00],
  ['WFC', 'Wells Fargo & Company', 'Bankacılık & Tüketici Kredileri', 74.00],
  ['VZ', 'Verizon Communications', 'Telekomünikasyon & Kablosuz Ağ', 42.50],
  ['AMAT', 'Applied Materials Inc.', 'Yarı İletken Üretim Ekipmanları', 185.00],
  ['INTU', 'Intuit Inc.', 'Mali ve Muhasebe Yazılımları', 665.00],
  ['NOW', 'ServiceNow Inc.', 'Kurumsal İş Akışı Otomasyonu', 1040.00],
  ['CMG', 'Chipotle Mexican Grill', 'Hızlı Rahat Restoranlar', 62.00],
  ['ISRG', 'Intuitive Surgical Inc.', 'Robotik Cerrahi Sistemleri', 535.00],
  ['BKNG', 'Booking Holdings Inc.', 'Online Seyahat & Konaklama', 4850.00],
  ['AMGN', 'Amgen Inc.', 'Biyoteknoloji & Terapötikler', 285.00],
  ['COP', 'ConocoPhillips', 'Petrol & Doğalgaz Arama/Üretim', 108.00],
  ['HON', 'Honeywell International', 'Endüstriyel Otomasyon & Havacılık', 225.00],
  ['UNP', 'Union Pacific Corporation', 'Demiryolu Taşımacılığı & Lojistik', 238.00],
  ['AXP', 'American Express Company', 'Ödeme Kartları & Finansal Hizmetler', 285.00],
  ['LOW', 'Lowe\'s Companies Inc.', 'Ev Geliştirme Perakendeciliği', 265.00],
  ['BLK', 'BlackRock Inc.', 'Global Varlık & Portföy Yönetimi', 1025.00],
  ['NEE', 'NextEra Energy Inc.', 'Yenilenebilir & Temiz Enerji', 78.00],
  ['TJX', 'The TJX Companies Inc.', 'İndirimli Giyim & Ev Modası', 122.00],
  ['SPGI', 'S&P Global Inc.', 'Finansal Derecelendirme & Veri', 510.00],
  ['SYK', 'Stryker Corporation', 'Tıbbi Teknoloji & Ortopedi', 385.00],
  ['GS', 'The Goldman Sachs Group', 'Yatırım Bankacılığı & Aracılık', 585.00],
  ['BA', 'The Boeing Company', 'Ticari & Askeri Uçak Üretimi', 158.00],
  ['DHR', 'Danaher Corporation', 'Yaşam Bilimleri & Tanı Cihazları', 242.00],
  ['ETN', 'Eaton Corporation plc', 'Güç Yönetimi & Elektrik Sistemleri', 365.00],
  ['MDT', 'Medtronic plc', 'Tıbbi Cihazlar & Sağlık Çözümleri', 88.00],
  ['REGN', 'Regeneron Pharmaceuticals', 'Biyoteknoloji & Antikor İlaçları', 765.00],
  ['MS', 'Morgan Stanley', 'Yatırım Bankacılığı & Varlık Yönetimi', 128.00],
  ['VRTX', 'Vertex Pharmaceuticals', 'Kistik Fibrozis & Gen Düzenleme', 465.00],
  ['BSX', 'Boston Scientific Corp.', 'Girişimsel Tıp Cihazları', 88.50],
  ['PANW', 'Palo Alto Networks Inc.', 'Yeni Nesil Siber Güvenlik', 392.00],
  ['PLTR', 'Palantir Technologies Inc.', 'Büyük Veri Analitiği & AI Platformu', 68.50],
  ['MMC', 'Marsh & McLennan Companies', 'Sigorta Aracılığı & Risk Danışmanlığı', 228.00],
  ['CB', 'Chubb Limited', 'Mülk ve Kaza Sigortacılığı', 285.00],
  ['PGR', 'The Progressive Corporation', 'Oto & Mülk Sigortacılığı', 255.00],
  ['DE', 'Deere & Company', 'Tarım Makineleri & Hassas Tarım', 415.00],
  ['CI', 'The Cigna Group', 'Küresel Sağlık Hizmetleri & Eczane', 320.00],
  ['LMT', 'Lockheed Martin Corporation', 'Havacılık, Savunma & Füze Sistemleri', 545.00],
  ['LRCX', 'Lam Research Corporation', 'Yarı İletken Aşındırma Ekipmanları', 78.50],
  ['ELV', 'Elevance Health Inc.', 'Sağlık Planları & Medikal Hizmetler', 420.00],
  ['ADP', 'Automatic Data Processing', 'Bordro & İnsan Kaynakları Yazılımı', 295.00],
  ['GILD', 'Gilead Sciences Inc.', 'Biyofarmasötik & Antiviral Tedaviler', 92.00],
  ['ADI', 'Analog Devices Inc.', 'Sinyal İşleme & Analog Çipler', 222.00],
  ['MU', 'Micron Technology Inc.', 'Bellek Çipleri (DRAM & NAND)', 104.00],
  ['KLAC', 'KLA Corporation', 'Yarı İletken Süreç Kontrolü', 665.00],
  ['FI', 'Fiserv Inc.', 'Ödemeler & Finansal Teknoloji', 215.00],
  ['SNPS', 'Synopsys Inc.', 'Elektronik Tasarım Otomasyonu (EDA)', 540.00],
  ['CDNS', 'Cadence Design Systems', 'Çip Tasarım Yazılımları (EDA)', 295.00],
  ['BDX', 'Becton Dickinson and Co.', 'Tıbbi Malzemeler & Teşhis', 242.00],
  ['ICE', 'Intercontinental Exchange', 'Finansal Borsalar & Mortgage Verisi', 158.00],
  ['CRWD', 'CrowdStrike Holdings Inc.', 'Bulut Tabanlı Uç Nokta Güvenliği', 355.00],
  ['APH', 'Amphenol Corporation', 'Konnektörler & Fiber Optik Sensörler', 68.00],
  ['CMCSA', 'Comcast Corporation', 'Genişbant İnternet & Medya Eğlence', 42.00],
  ['WM', 'Waste Management Inc.', 'Atık Yönetimi & Geri Dönüşüm', 218.00],
  ['SO', 'The Southern Company', 'Elektrik & Kamu Hizmetleri', 88.00],
  ['MCO', 'Moody\'s Corporation', 'Kredi Derecelendirme & Risk Analitiği', 475.00],
  ['MO', 'Altria Group Inc.', 'Tütün & Tüketim Ürünleri', 54.00],
  ['EOG', 'EOG Resources Inc.', 'Kayaç Petrolü & Doğalgaz Üretimi', 132.00],
  ['ITW', 'Illinois Tool Works Inc.', 'Endüstriyel Ekipman & Malzemeler', 265.00],
  ['SHW', 'The Sherwin-Williams Company', 'Boya & Kaplama Ürünleri', 375.00],
  ['PYPL', 'PayPal Holdings Inc.', 'Dijital Cüzdan & Ödeme Çözümleri', 84.50],
  ['T', 'AT&T Inc.', 'Telekomünikasyon & 5G Altyapısı', 22.80],
  ['CVS', 'CVS Health Corporation', 'Eczane Zinciri & Sağlık Sigortası', 58.00],
  ['ECL', 'Ecolab Inc.', 'Su Arıtma, Hijyen & Enfeksiyon Önleme', 248.00],
  ['SLB', 'Schlumberger Limited', 'Petrol Sahası Hizmetleri & Teknoloji', 42.00],
  ['CTAS', 'Cintas Corporation', 'Kurumsal Üniforma & Tesis Hizmetleri', 198.00],
  ['DUK', 'Duke Energy Corporation', 'Elektrik & Gaz Dağıtımı', 114.00],
  ['PH', 'Parker-Hannifin Corporation', 'Hareket ve Kontrol Teknolojileri', 645.00],
  ['CL', 'Colgate-Palmolive Company', 'Ağız Bakımı & Kişisel Hijyen', 96.00],
  ['MCK', 'McKesson Corporation', 'İlaç Dağıtımı & Sağlık Tedarik', 580.00],
  ['AON', 'Aon plc', 'Risk Yönetimi & Sigorta Danışmanlığı', 375.00],
  ['CSX', 'CSX Corporation', 'Yük Demiryolu Taşımacılığı', 35.00],
  ['TDG', 'TransDigm Group Incorporated', 'Havacılık Yedek Parçaları & Sistemler', 1280.00],
  ['HCA', 'HCA Healthcare Inc.', 'Hastane & Cerrahi Merkezleri', 335.00],
  ['BMY', 'Bristol-Myers Squibb Company', 'Biyofarmasötik & İmmüno-onkoloji', 56.00],
  ['NXPI', 'NXP Semiconductors N.V.', 'Otomotiv & Endüstriyel Çipler', 235.00],
  ['MAR', 'Marriott International Inc.', 'Küresel Otel & Konaklama Zinciri', 278.00],
  ['ABNB', 'Airbnb Inc.', 'Online Konaklama & Deneyim Pazarı', 138.00],
  ['COIN', 'Coinbase Global Inc.', 'Kripto Para Borsası & Web3 Altyapı', 315.00],
  ['MSTR', 'MicroStrategy Incorporated', 'Bitcoin Rezerv Şirketi & İş Zekası', 385.00],
  ['ARM', 'Arm Holdings plc', 'Yarı İletken Mimari & IP Tasarımı', 138.00],
  ['SMCI', 'Super Micro Computer Inc.', 'AI Sunucuları & Sıvı Soğutma', 38.50],
  ['DELL', 'Dell Technologies Inc.', 'AI Sunucuları & Kurumsal Donanım', 134.00],
  ['INTC', 'Intel Corporation', 'Mikroişlemciler & Dökümhane (Foundry)', 22.50],
  ['ROST', 'Ross Stores Inc.', 'İndirimli Giyim Perakendesi', 148.00],
  ['FDX', 'FedEx Corporation', 'Küresel Ekspres Kargo & Lojistik', 285.00],
  ['EMR', 'Emerson Electric Co.', 'Endüstriyel Otomasyon & Süreç Kontrol', 128.00],
  ['NSC', 'Norfolk Southern Corp.', 'Demiryolu Taşımacılığı', 265.00],
  ['COR', 'Cencora Inc.', 'İlaç Dağıtımı & Sağlık Çözümleri', 242.00],
  ['PNC', 'The PNC Financial Services', 'Bölgesel Bankacılık & Varlık', 198.00],
  ['USB', 'U.S. Bancorp', 'Finansal Hizmetler & Bankacılık', 51.00],
  ['GD', 'General Dynamics Corporation', 'Savunma Sanayi, Denizaltı & Havacılık', 302.00],
  ['RTX', 'RTX Corporation (Raytheon)', 'Havacılık & Savunma Sistemleri', 124.00],
  ['NOC', 'Northrop Grumman Corp.', 'Hayalet Bombardıman & Uzay Sistemleri', 512.00],
  ['HLT', 'Hilton Worldwide Holdings', 'Otelcilik & Tatil Köyleri', 245.00],
  ['ORLY', 'O\'Reilly Automotive Inc.', 'Otomotiv Yedek Parça Perakende', 1210.00],
  ['AZO', 'AutoZone Inc.', 'Oto Yedek Parça & Aksesuar', 3140.00],
  ['ADSK', 'Autodesk Inc.', 'CAD & 3D Tasarım Yazılımları', 312.00],
  ['ROP', 'Roper Technologies Inc.', 'Niş Yazılım & Medikal Sistemler', 565.00],
  ['CPRT', 'Copart Inc.', 'Online Araç İhale & Müzayede', 56.00],
  ['PCAR', 'PACCAR Inc.', 'Ağır Hizmet Kamyonları (Kenworth/Peterbilt)', 112.00],
  ['MNST', 'Monster Beverage Corporation', 'Enerji İçecekleri & Meşrubat', 52.00],
  ['ODFL', 'Old Dominion Freight Line', 'LTL Kargo Taşımacılığı', 204.00],
  ['PAYX', 'Paychex Inc.', 'İK, Bordro & Yan Haklar Hizmeti', 142.00],
  ['FAST', 'Fastenal Company', 'Endüstriyel Bağlantı Elemanları', 82.00],
  ['CTSH', 'Cognizant Technology Solutions', 'BT Danışmanlığı & Yazılım', 76.00],
  ['VRSK', 'Verisk Analytics Inc.', 'Veri Analitiği & Risk Değerlendirme', 274.00],
  ['GEHC', 'GE HealthCare Technologies', 'Tıbbi Görüntüleme & Tanı Cihazları', 88.00],
  ['FANG', 'Diamondback Energy Inc.', 'Permian Havzası Petrol Üretimi', 184.00],
  ['KDP', 'Keurig Dr Pepper Inc.', 'Kahve Makineleri & Gazlı İçecekler', 34.00],
  ['CHTR', 'Charter Communications Inc.', 'Kablolu TV & Genişbant İnternet', 385.00],
  ['EXC', 'Exelon Corporation', 'Elektrik Dağıtım & İletim', 39.50],
  ['XEL', 'Xcel Energy Inc.', 'Elektrik & Doğalgaz Hizmetleri', 68.00],
  ['KMB', 'Kimberly-Clark Corporation', 'Kişisel Bakım & Hijyen Ürünleri', 138.00],
  ['STZ', 'Constellation Brands Inc.', 'Bira, Şarap & Alkollü İçecekler', 242.00],
  ['MET', 'MetLife Inc.', 'Hayat Sigortası & Emeklilik', 84.00],
  ['AIG', 'American International Group', 'Global Sigorta & Finans', 76.00],
  ['PRU', 'Prudential Financial Inc.', 'Sigorta & Finansal Danışmanlık', 122.00],
  ['TRV', 'The Travelers Companies', 'Ticari & Bireysel Sigortacılık', 265.00],
  ['ALL', 'The Allstate Corporation', 'Kişisel Hatlar Sigortacılığı', 198.00],
  ['AFL', 'Aflac Incorporated', 'Tamamlayıcı Sağlık Sigortası', 112.00],
  ['AMP', 'Ameriprise Financial Inc.', 'Varlık Yönetimi & Finansal Planlama', 545.00],
  ['TROW', 'T. Rowe Price Group Inc.', 'Yatırım Yönetimi & Emeklilik Fonları', 114.00],
  ['BK', 'The Bank of New York Mellon', 'Saklama Bankacılığı & Varlık Yönetimi', 78.00],
  ['STT', 'State Street Corporation', 'Kurumsal Yatırımcı Hizmetleri & ETF', 98.00],
  ['NTRS', 'Northern Trust Corporation', 'Özel Bankacılık & Varlık Saklama', 104.00],
  ['FITB', 'Fifth Third Bancorp', 'Bölgesel Ticari Bankacılık', 44.00],
  ['RF', 'Regions Financial Corporation', 'Güneydoğu ABD Bölgesel Bankacılık', 24.50],
  ['CFG', 'Citizens Financial Group', 'Bireysel & Ticari Bankacılık', 46.00],
  ['KEY', 'KeyCorp', 'Bölgesel Finansal Hizmetler', 18.50],
  ['HBAN', 'Huntington Bancshares Inc.', 'Orta Batı Bölgesel Bankacılığı', 16.80],
  ['MTB', 'M&T Bank Corporation', 'Topluluk & Ticari Bankacılık', 212.00],
  ['C', 'Citigroup Inc.', 'Global Yatırım Bankacılığı', 68.00],
  ['MSI', 'Motorola Solutions Inc.', 'Kamu Güvenliği & Telsiz Sistemleri', 485.00],
  ['ANET', 'Arista Networks Inc.', 'Bulut Ağ Anahtarları & Yazılım', 412.00],
  ['TEL', 'TE Connectivity Ltd.', 'Sensörler & Bağlantı Elemanları', 154.00],
  ['KEYS', 'Keysight Technologies Inc.', 'Elektronik Ölçüm & Test Cihazları', 162.00],
  ['FTNT', 'Fortinet Inc.', 'Ağ Güvenliği & Güvenlik Duvarı', 96.00],
  ['GEN', 'Gen Digital Inc.', 'Bireysel Siber Güvenlik (Norton/Avast)', 28.50],
  ['WDAY', 'Workday Inc.', 'Kurumsal Bulut İK & Finans', 274.00],
  ['TEAM', 'Atlassian Corporation', 'Yazılım Geliştirme & İşbirliği (Jira)', 248.00],
  ['DDOG', 'Datadog Inc.', 'Bulut İzleme & Güvenlik Analitiği', 142.00],
  ['SNOW', 'Snowflake Inc.', 'Bulut Veri Ambarı & AI Platformu', 178.00],
  ['NET', 'Cloudflare Inc.', 'Web Performansı & CDN / Zero Trust', 114.00],
  ['ZS', 'Zscaler Inc.', 'Bulut Güvenliği & SASE Çözümleri', 214.00],
  ['MDB', 'MongoDB Inc.', 'Modern Belge Tabanlı Veritabanı', 320.00],
  ['HUBS', 'HubSpot Inc.', 'Pazarlama & Müşteri Etkileşimi', 680.00],
  ['APP', 'AppLovin Corporation', 'Mobil Uygulama Pazarlama & AI', 345.00],
  ['TTD', 'The Trade Desk Inc.', 'Programatik Dijital Reklam Alımı', 124.00],
  ['SHOP', 'Shopify Inc.', 'E-Ticaret Altyapısı & Mağaza Çözümleri', 114.00],
  ['SE', 'Sea Limited', 'Güneydoğu Asya E-Ticaret & Oyun', 112.00],
  ['MELI', 'MercadoLibre Inc.', 'Latin Amerika E-Ticaret & Fintek', 2150.00],
  ['CP', 'Canadian Pacific Kansas City', 'Trans-Kıta Demiryolu Ağı', 84.00],
  ['CNI', 'Canadian National Railway', 'Kuzey Amerika Demiryolu Taşımacılığı', 112.00],
  ['DAL', 'Delta Air Lines Inc.', 'Küresel Havayolu Taşımacılığı', 62.00],
  ['UAL', 'United Airlines Holdings', 'Uluslararası Havayolu Taşımacılığı', 94.00],
  ['LUV', 'Southwest Airlines Co.', 'Düşük Maliyetli İç Hat Uçuşları', 32.00],
  ['AAL', 'American Airlines Group', 'Yolcu & Kargo Havayolu Hizmetleri', 15.80],
  ['GM', 'General Motors Company', 'Otomotiv & Elektrikli Araçlar', 54.00],
  ['F', 'Ford Motor Company', 'Kamyonet, SUV & Otomotiv', 11.20],
  ['RIVN', 'Rivian Automotive Inc.', 'Elektrikli Kamyonet & SUV', 12.40],
  ['LCID', 'Lucid Group Inc.', 'Lüks Elektrikli Sedanlar', 2.45],
  ['ON', 'ON Semiconductor Corp.', 'Güç Yönetimi & Otomotiv Çipleri', 74.00],
  ['MPWR', 'Monolithic Power Systems', 'Yüksek Performanslı Güç Çipleri', 640.00],
  ['SWKS', 'Skyworks Solutions Inc.', 'Kablosuz İletişim RF Yarı İletkenleri', 88.00],
  ['QRVO', 'Qorvo Inc.', 'RF Çözümleri & Mobil Bağlantı', 74.00],
  ['WDC', 'Western Digital Corp.', 'HDD & Flash Bellek Depolama', 68.00],
  ['STX_US', 'Seagate Technology Holdings', 'Kurumsal Veri Depolama (HDD)', 104.00],
  ['HPE', 'Hewlett Packard Enterprise', 'Kurumsal Sunucular & Edge Bulut', 21.50],
  ['HPQ', 'HP Inc.', 'Kişisel Bilgisayarlar & Yazıcılar', 36.50],
  ['NTAP', 'NetApp Inc.', 'Akıllı Veri Altyapısı & Depolama', 128.00],
  ['PSTG', 'Pure Storage Inc.', 'Tüm Flash Veri Depolama Sistemleri', 54.00],
  ['FFIV', 'F5 Inc.', 'Uygulama Güvenliği & Dağıtımı', 242.00],
  ['AKAM', 'Akamai Technologies Inc.', 'CDN, Bulut Bilişim & Siber Güvenlik', 94.00],
  ['TER', 'Teradyne Inc.', 'Otomatik Test Ekipmanları & Robotik', 122.00],
  ['ENTG', 'Entegris Inc.', 'Yarı İletken Saflık & Malzeme Çözümleri', 108.00],
  ['MKSI', 'MKS Instruments Inc.', 'Vakum & Lazer Proses Ekipmanları', 118.00],
  ['COHR', 'Coherent Corp.', 'Optik İletişim & Lazer Malzemeleri', 104.00],
  ['LITE', 'Lumentum Holdings Inc.', 'Optik & Fotonik Bileşenler', 84.00],
  ['CIEN', 'Ciena Corporation', 'Optik Ağ Sistemleri & Yazılım', 68.00],
  ['JNPR', 'Juniper Networks Inc.', 'Yapay Zeka Destekli Ağ Çözümleri', 38.00],
  ['SMTC', 'Semtech Corporation', 'LoRa & Yüksek Performanslı Analog', 54.00],
  ['ALAB', 'Astera Labs Inc.', 'AI ve Bulut Bağlantı Çipleri', 98.00],
  ['CAVA', 'CAVA Group Inc.', 'Akdeniz Mutfağı Restoran Zinciri', 142.00],
  ['WING', 'Wingstop Inc.', 'Tavuk Kanadı Restoran Franchise', 365.00],
  ['DPZ', 'Domino\'s Pizza Inc.', 'Global Pizza Teslimat Zinciri', 445.00],
  ['YUM', 'YUM! Brands Inc.', 'KFC, Pizza Hut, Taco Bell', 138.00],
  ['DRI', 'Darden Restaurants Inc.', 'Olive Garden & LongHorn Steakhouse', 178.00],
  ['SBUX', 'Starbucks Corporation', 'Özel Kahve & Mağazacılık', 98.50],
  ['QSR', 'Restaurant Brands International', 'Burger King, Tim Hortons, Popeyes', 72.00],
  ['EXPE', 'Expedia Group Inc.', 'Online Seyahat & Rezervasyon', 178.00],
  ['TRIP', 'Tripadvisor Inc.', 'Seyahat İnceleme & Rezervasyon', 16.50],
  ['RCL', 'Royal Caribbean Cruises Ltd.', 'Lüks Kruvaziyer Tatil Turları', 235.00],
  ['CCL', 'Carnival Corporation & plc', 'Dünya Çapında Kruvaziyer Hatları', 25.40],
  ['NCLH', 'Norwegian Cruise Line Holdings', 'Kruvaziyer Seyahatleri', 26.80],
  ['WYNN', 'Wynn Resorts Limited', 'Lüks Casino & Otel Kompleksleri', 94.00],
  ['LVS', 'Las Vegas Sands Corp.', 'Asya ve ABD Casino & Tatil Köyleri', 54.00],
  ['MGM', 'MGM Resorts International', 'Casino, Otel & Eğlence Merkezleri', 38.50],
  ['DKNG', 'DraftKings Inc.', 'Online Spor Bahisleri & İ-Gaming', 44.00],
  ['PENN', 'PENN Entertainment Inc.', 'Kumarhane & Dijital Bahis', 21.00],
  ['TTWO', 'Take-Two Interactive Software', 'GTA, 2K Sports Video Oyunları', 184.00],
  ['EA', 'Electronic Arts Inc.', 'EA Sports FC, Apex Legends', 162.00],
  ['RBLX', 'Roblox Corporation', 'Kullanıcı Üretimi Oyun & Metaverse', 54.00],
  ['U', 'Unity Software Inc.', 'Gerçek Zamanlı 3D Oyun Motoru', 24.50],
  ['PLNT', 'Planet Fitness Inc.', 'Düşük Ücretli Fitness Salonları', 98.00],
  ['NKE', 'NIKE Inc.', 'Spor Ayakkabı, Giyim & Ekipman', 78.00],
  ['LULU', 'Lululemon Athletica Inc.', 'Yoga & Teknik Spor Giyim', 345.00],
  ['DECK', 'Deckers Outdoor Corporation', 'HOKA, UGG Spor Ayakkabıları', 198.00],
  ['ONON', 'On Holding AG', 'Premium Koşu Ayakkabıları (On Cloud)', 54.00],
  ['CROX', 'Crocs Inc.', 'Rahat Ayakkabılar & HEYDUDE', 114.00],
  ['SKX', 'Skechers U.S.A. Inc.', 'Yaşam Tarzı & Performans Ayakkabıları', 64.00],
  ['ELF', 'e.l.f. Beauty Inc.', 'Temiz & Uygun Fiyatlı Kozmetik', 128.00],
  ['ULTA', 'Ulta Beauty Inc.', 'Güzellik Ürünleri & Salon Hizmetleri', 395.00],
  ['EL', 'The Estée Lauder Companies', 'Lüks Cilt Bakımı & Parfüm', 68.00],
  ['COTY', 'Coty Inc.', 'Kozmetik & Parfüm Markaları', 7.40],
  ['KSS', 'Kohl\'s Corporation', 'Büyük Mağazacılık Zinciri', 16.50],
  ['M', 'Macy\'s Inc.', 'Lüks & Moda Büyük Mağazacılık', 16.80],
  ['JWN', 'Nordstrom Inc.', 'Lüks Moda & Giyim Mağazaları', 24.00],
  ['BBY', 'Best Buy Co. Inc.', 'Tüketici Elektroniği Perakendecisi', 92.00],
  ['TGT', 'Target Corporation', 'Genel Mağazacılık & Perakende', 134.00],
  ['DG', 'Dollar General Corporation', 'İndirimli Mahalle Perakendecisi', 76.00],
  ['DLTR', 'Dollar Tree Inc.', 'İndirimli Çeşit Mağazaları', 74.00],
  ['FIVE', 'Five Below Inc.', 'Gençler İçin İndirimli Trend Ürünler', 104.00],
  ['OLLI', 'Ollie\'s Bargain Outlet Holdings', 'İndirimli İhraç Fazlası Perakende', 94.00],
  ['WBA', 'Walgreens Boots Alliance', 'Eczane & Sağlık Perakendecisi', 9.80],
  ['KR', 'The Kroger Co.', 'Süpermarket & Çoklu Format Perakende', 58.00],
  ['SYY', 'Sysco Corporation', 'Restoran & Otel Gıda Dağıtımı', 78.00],
  ['USFD', 'US Foods Holding Corp.', 'Gıda Servisi Distribütörü', 64.00],
  ['PFGC', 'Performance Food Group Co.', 'Ticari Gıda Hizmeti Dağıtımı', 84.00],
  ['GIS', 'General Mills Inc.', 'Kahvaltılık Gevrek & Paketli Gıda', 64.00],
  ['K', 'Kellanova', 'Pringles, Cheez-It Atıştırmalıklar', 81.00],
  ['MDLZ', 'Mondelez International Inc.', 'Oreo, Milka, Cadbury Atıştırmalık', 66.00],
  ['HSY', 'The Hershey Company', 'Çikolata & Şekerleme Ürünleri', 178.00],
  ['CPB', 'Campbell Soup Company', 'Çorba, Sos & Kraker Ürünleri', 44.00],
  ['CAG', 'Conagra Brands Inc.', 'Dondurulmuş & Paketli Gıdalar', 28.00],
  ['SJM', 'The J. M. Smucker Company', 'Reçel, Fıstık Ezmesi & Kahve', 114.00],
  ['HRL', 'Hormel Foods Corporation', 'Et Ürünleri & Konserve Gıdalar', 31.00],
  ['TSN', 'Tyson Foods Inc.', 'Tavuk, Sığır & Domuz Eti İşleme', 58.00],
  ['PPC', 'Pilgrim\'s Pride Corporation', 'Kanatlı Hayvan Üretimi', 48.00],
  ['CALM', 'Cal-Maine Foods Inc.', 'Yumurta Üretimi & Dağıtımı', 92.00],
  ['ADM', 'Archer-Daniels-Midland Co.', 'Tarımsal Emtia İşleme & Tahıl', 54.00],
  ['BG', 'Bunge Global SA', 'Yağlı Tohum İşleme & Tarım İhracatı', 88.00],
  ['DAR', 'Darling Ingredients Inc.', 'Biyo-besin & Sürdürülebilir Yakıt', 42.00],
  ['MOS', 'The Mosaic Company', 'Fosfat & Potas Gübre Üretimi', 26.50],
  ['NTR', 'Nutrien Ltd.', 'Azot, Potas & Tarımsal Çözümler', 48.00],
  ['CF', 'CF Industries Holdings Inc.', 'Azotlu Gübre & Temiz Amonyak', 88.00],
  ['FMC', 'FMC Corporation', 'Zirai İlaç & Bitki Sağlığı Kimyası', 58.00],
  ['CTVA', 'Corteva Inc.', 'Tohum Teknolojileri & Tarım Kimyası', 58.00],
  ['ALB', 'Albemarle Corporation', 'Lityum Üretimi & Özel Kimyasallar', 98.00],
  ['SQM', 'Sociedad Química y Minera', 'Lityum & Özel Bitki Besleme', 38.50],
  ['FCX', 'Freeport-McMoRan Inc.', 'Bakır & Altın Madenciliği', 44.00],
  ['SCCO', 'Southern Copper Corporation', 'Bakır Madenciliği & İzabe', 108.00],
  ['NEM', 'Newmont Corporation', 'Dünyanın En Büyük Altın Madencisi', 42.00],
  ['GOLD', 'Barrick Gold Corporation', 'Küresel Altın ve Bakır Madenciliği', 18.20],
  ['AEM', 'Agnico Eagle Mines Limited', 'Kıymetli Maden & Altın Üretimi', 84.00],
  ['WPM', 'Wheaton Precious Metals Corp.', 'Değerli Metal Telif Hakları (Streaming)', 64.00],
  ['FNV', 'Franco-Nevada Corporation', 'Altın Telif & Royalty Şirketi', 128.00],
  ['RGLD', 'Royal Gold Inc.', 'Kıymetli Madenler Telif Portföyü', 142.00],
  ['AA', 'Alcoa Corporation', 'Boksit, Alümina & Alüminyum İmalatı', 42.00],
  ['CENX', 'Century Aluminum Company', 'Birincil Alüminyum Üretimi', 18.50],
  ['X', 'United States Steel Corporation', 'Entegre Yassı Çelik İmalatı', 39.00],
  ['NUE', 'Nucor Corporation', 'Mini-Mill Elektrik Ark Ocaklı Çelik', 148.00],
  ['STLD', 'Steel Dynamics Inc.', 'Karbon Çelik & Geri Dönüşüm', 134.00],
  ['CLF', 'Cleveland-Cliffs Inc.', 'Otomotiv Yassı Çelik & Demir Cevheri', 12.80],
  ['VALE', 'Vale S.A.', 'Demir Cevheri, Nikel & Pelet', 9.80],
  ['BHP', 'BHP Group Limited', 'Çeşitlendirilmiş Küresel Madencilik', 52.00],
  ['RIO', 'Rio Tinto Group', 'Demir Cevheri, Alüminyum & Bakır', 62.00],
  ['GLNCY', 'Glencore plc', 'Doğal Kaynaklar & Emtia Ticareti', 9.80],
  ['OXY', 'Occidental Petroleum Corp.', 'Petrol, Gaz & Karbon Yakalama', 51.00],
  ['HES', 'Hess Corporation', 'Guyana Derin Deniz Petrol Üretimi', 148.00],
  ['DVN', 'Devon Energy Corporation', 'ABD Karasal Petrol & Sıvı Gaz', 39.00],
  ['MRO', 'Marathon Oil Corporation', 'Unconventional Petrol & Doğalgaz', 28.50],
  ['APA', 'APA Corporation', 'Küresel Enerji Arama & Üretim', 24.00],
  ['VLO', 'Valero Energy Corporation', 'Petrol Rafinerisi & Yenilenebilir Dizel', 138.00],
  ['MPC', 'Marathon Petroleum Corp.', 'Rafineri, Pazarlama & Lojistik', 154.00],
  ['PSX', 'Phillips 66', 'Rafineri, Kimyasallar & Orta Akım', 128.00],
  ['HESM', 'Hess Midstream LP', 'Petrol Boru Hatları & Terminal', 38.00],
  ['WMB', 'The Williams Companies Inc.', 'Doğalgaz Boru Hattı Altyapısı', 54.00],
  ['KMI', 'Kinder Morgan Inc.', 'Kuzey Amerika Enerji Altyapısı', 26.50],
  ['OKE', 'ONEOK Inc.', 'Doğalgaz Sıvıları Toplama & Taşıma', 104.00],
  ['TRGP', 'Targa Resources Corp.', 'Orta Akım Doğalgaz Hizmetleri', 188.00],
  ['ET', 'Energy Transfer LP', 'Ham Petrol & Gaz Boru Hatları', 18.20],
  ['EPD', 'Enterprise Products Partners', 'Entegre Enerji Orta Akım Hizmetleri', 31.00],
  ['MPLX', 'MPLX LP', 'Yakıt Toplama, İşleme & Taşıma', 46.00],
  ['HAL', 'Halliburton Company', 'Kuyu Tamamlama & Sondaj Hizmetleri', 29.50],
  ['BKR', 'Baker Hughes Company', 'Petrol Sahası Teknolojileri & Turbomakine', 42.00],
  ['NOV', 'NOV Inc.', 'Petrol Sondaj Ekipmanları & Kuleler', 15.80],
  ['FTI', 'TechnipFMC plc', 'Denizaltı Enerji Sistemleri', 28.00],
  ['FSLR', 'First Solar Inc.', 'İnce Film Güneş Enerjisi Panelleri', 198.00],
  ['ENPH', 'Enphase Energy Inc.', 'Mikroinverter & Ev Batarya Sistemleri', 68.00],
  ['SEDG', 'SolarEdge Technologies Inc.', 'Solar Optimize Edici & İnverter', 14.50],
  ['RUN', 'Sunrun Inc.', 'Konut Tipi Güneş Enerjisi & Depolama', 11.20],
  ['BE', 'Bloom Energy Corporation', 'Katı Oksit Yakıt Pilleri & Hidrojen', 22.00],
  ['PLUG', 'Plug Power Inc.', 'Yeşil Hidrojen & Yakıt Hücreleri', 2.15],
  ['CWEN', 'Clearway Energy Inc.', 'Temiz Enerji Üretim Tesisleri', 26.50],
  ['HASI', 'Hannon Armstrong Sustainable', 'İklim Çözümleri Finansmanı', 28.00],
  ['CEG', 'Constellation Energy Corp.', 'Nükleer Enerji & AI Veri Merkezi Gücü', 235.00],
  ['VST', 'Vistra Corp.', 'Nükleer, Gaz & Güneş Elektrik Üretimi', 154.00],
  ['NRG', 'NRG Energy Inc.', 'Tüketici Enerji Hizmetleri', 94.00],
  ['TLN', 'Talen Energy Corporation', 'Nükleer Güç & Bulut Veri Merkezi', 215.00],
  ['AEE', 'Ameren Corporation', 'Elektrik & Gaz Kamu Hizmeti', 88.00],
  ['AEP', 'American Electric Power Co.', 'Bölgesel Elektrik Dağıtımı', 98.00],
  ['D', 'Dominion Energy Inc.', 'Temiz Enerji & Elektrik Şebekesi', 56.00],
  ['ED', 'Consolidated Edison Inc.', 'New York Elektrik & Gaz Şebekesi', 98.00],
  ['EIX', 'Edison International', 'Güney Kaliforniya Elektrik Hizmeti', 84.00],
  ['ES', 'Eversource Energy', 'New England Enerji Dağıtımı', 64.00],
  ['ETR', 'Entergy Corporation', 'Güney Eyaletleri Elektrik Üretimi', 88.00],
  ['FE', 'FirstEnergy Corp.', 'Orta Atlantik Elektrik Şebekesi', 42.00],
  ['PPL', 'PPL Corporation', 'Düzenlemeye Tabi Elektrik Şirketi', 32.00],
  ['PEG', 'Public Service Enterprise Group', 'Nükleer & Gaz Kamu Hizmeti', 86.00],
  ['SRE', 'Sempra', 'LNG İhracatı & Altyapı Şebekesi', 88.00],
  ['WEC', 'WEC Energy Group Inc.', 'Midwest Elektrik & Gaz Sağlayıcısı', 94.00],
  ['AWK', 'American Water Works Co.', 'Su ve Atıksu Hizmetleri', 134.00],
  ['WTRG', 'Essential Utilities Inc.', 'Su ve Doğalgaz Dağıtımı', 38.00],
  ['XYL', 'Xylem Inc.', 'Su Teknolojileri & Akıllı Sayaçlar', 128.00],
  ['PLD', 'Prologis Inc.', 'Lojistik & E-Ticaret Depo GYO', 118.00],
  ['AMT', 'American Tower Corporation', 'Kablosuz İletişim Kuleleri GYO', 198.00],
  ['CCI', 'Crown Castle Inc.', 'Hücresel Kuleler & Küçük Hücre Ağı', 104.00],
  ['EQIX', 'Equinix Inc.', 'Küresel Taşıyıcı Bağımsız Veri Merkezleri', 945.00],
  ['DLR', 'Digital Realty Trust Inc.', 'Bulut & AI Veri Merkezleri GYO', 178.00],
  ['PSA', 'Public Storage', 'Bireysel Kiralık Depolama GYO', 315.00],
  ['EXR', 'Extra Space Storage Inc.', 'Kişisel Depolama Tesisleri', 158.00],
  ['O', 'Realty Income Corporation', 'Aylık Temettü Ödeyen Perakende GYO', 54.00],
  ['NNN', 'NNN REIT Inc.', 'Tek Kiracılı Net Kiralık Mülkler', 42.50],
  ['SPG', 'Simon Property Group Inc.', 'Lüks Alışveriş Merkezleri & Outletler', 174.00],
  ['VICI', 'VICI Properties Inc.', 'Las Vegas Casino & Otel Mülkleri', 32.00],
  ['GLPI', 'Gaming and Leisure Properties', 'Kumarhane & Eğlence Gayrimenkulleri', 49.00],
  ['WELL', 'Welltower Inc.', 'Kıdemli Yaşam Evleri & Sağlık GYO', 134.00],
  ['VTR', 'Ventas Inc.', 'Sağlık Tesisleri & Yaşlı Bakım Evleri', 64.00],
  ['AVB', 'AvalonBay Communities Inc.', 'Lüks Çok Aileli Konut Daireleri', 228.00],
  ['EQR', 'Equity Residential', 'Şehir İçi Yüksek Kaliteli Apartmanlar', 74.00],
  ['INVH', 'Invitation Homes Inc.', 'Tek Aileli Kiralık Konut Portföyü', 34.00],
  ['AMH', 'American Homes 4 Rent', 'Kiralık Müstakil Evler', 38.00],
  ['CPT', 'Camden Property Trust', 'Güneş Kuşağı Konut Toplulukları', 114.00],
  ['MAA', 'Mid-America Apartment Communities', 'Güneydoğu ABD Çok Aileli Konutlar', 158.00],
  ['UDR', 'UDR Inc.', 'Apartman Konut Geliştirme & Yönetim', 42.00],
  ['BXP', 'BXP Inc. (Boston Properties)', 'A Sınıfı Ofis Gökdelenleri GYO', 78.00],
  ['KRC', 'Kilroy Realty Corporation', 'Batı Yakası Ofis & Yaşam Bilimleri', 39.00],
  ['ARE', 'Alexandria Real Estate Equities', 'Yaşam Bilimleri & Laboratuvar Kampüsleri', 108.00],
  ['SBAC', 'SBA Communications Corp.', 'Kablosuz İletişim Altyapısı', 225.00],
  ['CBRE', 'CBRE Group Inc.', 'Ticari Gayrimenkul Hizmetleri & Aracılık', 138.00],
  ['JLL', 'Jones Lang LaSalle Inc.', 'Küresel Emlak Danışmanlığı & Değerleme', 265.00],
  ['CWK', 'Cushman & Wakefield plc', 'Gayrimenkul Yönetimi & Kiralama', 14.50],
  // Additional 130 S&P 500 & Nasdaq 100 Companies
  ['ABT', 'Abbott Laboratories', 'Tanı, Tıbbi Cihazlar & Beslenme', 118.00],
  ['ACGL', 'Arch Capital Group Ltd.', 'Özel Sigorta & Reasürans', 102.00],
  ['AEE_US', 'Ameren Corporation Energy', 'Bölgesel Elektrik & Gaz', 84.00],
  ['AES', 'The AES Corporation', 'Küresel Enerji & Yenilenebilir', 14.20],
  ['AJG', 'Arthur J. Gallagher & Co.', 'Sigorta Aracılığı & Risk Yönetimi', 295.00],
  ['AKAM_US', 'Akamai Technologies', 'Güvenlik & CDN', 94.50],
  ['ALGN', 'Align Technology Inc.', 'Invisalign Şeffaf Plak & 3D Tarayıcı', 215.00],
  ['AME', 'AMETEK Inc.', 'Elektronik Aletler & Elektromekanik', 184.00],
  ['AMCR', 'Amcor plc', 'Küresel Ambalaj Çözümleri', 10.40],
  ['ANSS', 'ANSYS Inc.', 'Mühendislik Simülasyon Yazılımları', 340.00],
  ['AOS', 'A. O. Smith Corporation', 'Su Isıtıcıları & Kazan Sistemleri', 78.00],
  ['APTV', 'Aptiv PLC', 'Otomotiv Elektroniği & Otonom Sistemler', 68.00],
  ['ATO', 'Atmos Energy Corporation', 'Doğalgaz Dağıtım Şebekesi', 142.00],
  ['BALL', 'Ball Corporation', 'Alüminyum İçecek Kutuları', 62.00],
  ['BAX', 'Baxter International Inc.', 'Diyaliz & Hastane Medikal Ürünleri', 34.00],
  ['BBY_US', 'Best Buy Retail', 'Tüketici Elektroniği', 91.00],
  ['BEN', 'Franklin Resources Inc.', 'Franklin Templeton Varlık Yönetimi', 22.40],
  ['BIO', 'Bio-Rad Laboratories Inc.', 'Yaşam Bilimi Araştırma & Klinik Tanı', 345.00],
  ['BLDR', 'Builders FirstSource Inc.', 'Yapı Malzemeleri & Prefabrik Çözümler', 184.00],
  ['BMRN', 'BioMarin Pharmaceutical', 'Nadir Genetik Hastalık Tedavileri', 68.00],
  ['BR', 'Broadridge Financial Solutions', 'Yatırımcı İletişimi & Fintek', 224.00],
  ['BRO', 'Brown & Brown Inc.', 'Sigorta Aracılığı & Risk Yönetimi', 104.00],
  ['BWA', 'BorgWarner Inc.', 'Otomotiv Güç Aktarım & Turbo', 34.00],
  ['CBOE', 'Cboe Global Markets Inc.', 'Opsiyon & Volatilite Borsaları', 214.00],
  ['CDW', 'CDW Corporation', 'Kurumsal BT Çözümleri & Donanım', 225.00],
  ['CE', 'Celanese Corporation', 'Özel Malzemeler & Kimyasallar', 82.00],
  ['CINF', 'Cincinnati Financial Corp.', 'Mülk & Kaza Sigortası', 142.00],
  ['CLX', 'The Clorox Company', 'Temizlik & Tüketici Ürünleri', 165.00],
  ['CMA', 'Comerica Incorporated', 'Ticari & Bireysel Bankacılık', 64.00],
  ['CME', 'CME Group Inc.', 'Dünyanın En Büyük Türev Borsası', 234.00],
  ['CMS', 'CMS Energy Corporation', 'Michigan Elektrik & Gaz Hizmeti', 68.00],
  ['CNP', 'CenterPoint Energy Inc.', 'Elektrik İletim & Gaz Dağıtımı', 31.00],
  ['COO', 'The Cooper Companies Inc.', 'Kontakt Lensler & Kadın Sağlığı', 104.00],
  ['CPAY', 'Corpay Inc.', 'Kurumsal Ödemeler & Yakıt Kartları', 365.00],
  ['CPB_US', 'Campbell Soup Products', 'Paketli Gıda Ürünleri', 43.50],
  ['CPT_US', 'Camden Property', 'Çok Aileli Konutlar', 114.50],
  ['CRL', 'Charles River Laboratories', 'İlaç Keşfi & Klinik Öncesi Test', 198.00],
  ['CTRA', 'Coterra Energy Inc.', 'Permian & Marcellus Petrol/Gaz', 26.50],
  ['CZR', 'Caesars Entertainment Inc.', 'Casino & Eğlence Merkezleri', 42.00],
  ['DAY', 'Dayforce Inc.', 'Bulut Bordro & İK Yönetimi', 74.00],
  ['DECK_US', 'Deckers Brands', 'Ayakkabı & Giyim', 198.50],
  ['DFS', 'Discover Financial Services', 'Kredi Kartı & Tüketici Bankacılığı', 168.00],
  ['DGX', 'Quest Diagnostics Inc.', 'Klinik Tanı & Laboratuvar Testleri', 158.00],
  ['DHI', 'D.R. Horton Inc.', 'Amerika\'nın En Büyük Konut İnşaatçısı', 178.00],
  ['DLR_US', 'Digital Realty', 'Veri Merkezi GYO', 178.50],
  ['DLTR_US', 'Dollar Tree Stores', 'İndirimli Perakende', 74.50],
  ['DOC', 'Healthpeak Properties Inc.', 'Sağlık Gayrimenkulleri & Laboratuvarlar', 21.00],
  ['DOV', 'Dover Corporation', 'Endüstriyel Ürünler & Mühendislik', 198.00],
  ['DOW', 'Dow Inc.', 'Temel Kimyasallar & Plastikler', 51.00],
  ['DTE', 'DTE Energy Company', 'Detroit Elektrik & Gaz Hizmeti', 124.00],
  ['DXCM', 'DexCom Inc.', 'Sürekli Glikoz İzleme (CGM) Cihazları', 74.00],
  ['EA_US', 'Electronic Arts Games', 'Video Oyunları & Eğlence', 162.50],
  ['EBAY', 'eBay Inc.', 'Online Pazar Yeri & E-Ticaret', 64.00],
  ['EG', 'Everest Group Ltd.', 'Reasürans & Özel Sigorta', 385.00],
  ['EMN', 'Eastman Chemical Company', 'Özel Kimyasallar & Malzemeler', 104.00],
  ['EPAM', 'EPAM Systems Inc.', 'Dijital Platform Mühendisliği', 234.00],
  ['EQT', 'EQT Corporation', 'ABD\'nin En Büyük Doğalgaz Üreticisi', 44.00],
  ['ERIE', 'Erie Indemnity Company', 'Mülk & Kaza Sigorta Yönetimi', 412.00],
  ['ESS', 'Essex Property Trust Inc.', 'Batı Yakası Konut Apartmanları', 295.00],
  ['ETR_US', 'Entergy Power', 'Elektrik Üretimi & İletimi', 88.50],
  ['EVRG', 'Evergy Inc.', 'Kansas & Missouri Elektrik Şebekesi', 61.00],
  ['EW', 'Edwards Lifesciences Corp.', 'Kalp Kapakçığı & Hemodinamik İzleme', 72.00],
  ['EXPD', 'Expeditors International', 'Küresel Lojistik & Nakliye Aracılığı', 124.00],
  ['EXPE_US', 'Expedia Travel Group', 'Online Seyahat Platformu', 178.50],
  ['EXR_US', 'Extra Space REIT', 'Kiralık Depolama', 158.50],
  ['FDS', 'FactSet Research Systems', 'Finansal Veri & Analitik Terminali', 485.00],
  ['FE_US', 'FirstEnergy Ohio', 'Elektrik Dağıtım Ağı', 42.50],
  ['FFIV_US', 'F5 Networks', 'Siber Güvenlik & Uygulama Dağıtım', 242.50],
  ['FICO', 'Fair Isaac Corporation', 'FICO Kredi Puanlama & Karar Analitiği', 2140.00],
  ['FMC_US', 'FMC Agrochemical', 'Tarım Kimyasalları', 58.50],
  ['FOX', 'Fox Corporation (Class B)', 'Haber & Canlı Spor Yayıncılığı', 42.00],
  ['FOXA', 'Fox Corporation (Class A)', 'Haber & Eğlence Medyası', 44.00],
  ['FRT', 'Federal Realty Investment Trust', 'Lüks AVM & Karma Yaşam GYO', 108.00],
  ['FSLR_US', 'First Solar Panels', 'Güneş Paneli Üretimi', 198.50],
  ['FTNT_US', 'Fortinet Network Security', 'Güvenlik Duvarı & SASE', 96.50],
  ['FTV', 'Fortive Corporation', 'Endüstriyel Teknoloji & Ölçüm Cihazları', 78.00],
  ['GD_US', 'General Dynamics Defense', 'Savunma Sanayi & Denizaltı', 302.50],
  ['GEHC_US', 'GE HealthCare Imaging', 'Medikal Cihazlar & Tanı', 88.50],
  ['GEN_US', 'Gen Digital Cyber', 'Tüketici Güvenlik Yazılımı', 28.60],
  ['GL', 'Globe Life Inc.', 'Hayat ve Ek Sağlık Sigortası', 108.00],
  ['GLW', 'Corning Incorporated', 'Özel Cam, Seramik & Gorilla Glass', 48.00],
  ['GPC', 'Genuine Parts Company', 'NAPA Otomotiv & Sanayi Yedek Parça', 128.00],
  ['GPN', 'Global Payments Inc.', 'Ticari Ödeme İşleme Teknolojileri', 104.00],
  ['GRMN', 'Garmin Ltd.', 'GPS Navigasyon, Akıllı Saat & Havacılık', 212.00],
  ['GWW', 'W.W. Grainger Inc.', 'Bakım, Onarım & İşletme (MRO) Tedarik', 1040.00],
  ['HES_US', 'Hess Oil & Gas', 'Derin Deniz Petrol Üretimi', 148.50],
  ['HIG', 'The Hartford Financial Services', 'Mülk, Kaza & Grup Yan Hakları Sigortası', 118.00],
  ['HII', 'Huntington Ingalls Industries', 'Nükleer Askeri Gemi & Denizaltı İnşası', 242.00],
  ['HOLX', 'Hologic Inc.', 'Kadın Sağlığı & Mamografi Teşhis', 78.00],
  ['HON_US', 'Honeywell Aerospace', 'Havacılık & Otomasyon', 225.50],
  ['HPE_US', 'Hewlett Packard Servers', 'Kurumsal Bulut & Sunucu', 21.60],
  ['HPQ_US', 'HP Personal Systems', 'PC & Yazıcı Donanımı', 36.60],
  ['HRL_US', 'Hormel Foods Meat', 'Paketli Et & Gıda', 31.20],
  ['HSIC', 'Henry Schein Inc.', 'Diş & Medikal Sağlık Malzemeleri', 74.00],
  ['HST', 'Host Hotels & Resorts Inc.', 'Lüks Otel & Tatil Köyü GYO', 18.20],
  ['HUBB', 'Hubbell Incorporated', 'Elektrik ve Şebeke Altyapı Ürünleri', 435.00],
  ['HUM', 'Humana Inc.', 'Medicare Sağlık Sigortası & Bakım', 278.00],
  ['HWM', 'Howmet Aerospace Inc.', 'Havacılık Motor Parçaları & Titanyum', 114.00],
  ['IBM_US', 'IBM Cloud & AI', 'Kurumsal Bilişim', 228.50],
  ['IDXX', 'IDEXX Laboratories Inc.', 'Veterinerlik Tanı & Hayvan Sağlığı', 440.00],
  ['IEX', 'IDEX Corporation', 'Akışkan Kontrol & Hassas Pompalar', 218.00],
  ['IFF', 'International Flavors & Fragrances', 'Tatlar, Kokular & Biyo-malzemeler', 88.00],
  ['INCY', 'Incyte Corporation', 'Biyofarmasötik & Hematoloji İlaçları', 72.00],
  ['INSM', 'Insmed Incorporated', 'Nadir Akciğer Hastalıkları Tedavisi', 74.00],
  ['IP', 'International Paper Company', 'Endüstriyel Ambalaj & Selüloz', 54.00],
  ['IPG', 'The Interpublic Group of Companies', 'Küresel Reklamcılık & Pazarlama', 29.50],
  ['IQV', 'IQVIA Holdings Inc.', 'Klinik Araştırma & Sağlık Verisi Analitiği', 215.00],
  ['IR', 'Ingersoll Rand Inc.', 'Endüstriyel Kompresör & Hava Sistemleri', 98.00],
  ['IRM', 'Iron Mountain Incorporated', 'Veri Depolama & Bilgi Yönetimi GYO', 114.00],
  ['ISRG_US', 'Intuitive Surgical Robot', 'Robotik Ameliyat Sistemleri', 535.50],
  ['IT', 'Gartner Inc.', 'BT & Teknoloji Pazar Araştırması', 525.00],
  ['ITT', 'ITT Inc.', 'Mühendislik Kritik Bileşenleri', 148.00],
  ['JBHT', 'J.B. Hunt Transport Services', 'Intermodal Taşımacılık & Kamyon Filosu', 178.00],
  ['JKHY', 'Jack Henry & Associates Inc.', 'Bankacılık & Fintek Yazılımları', 178.00],
  ['JNJ_US', 'Johnson & Johnson Healthcare', 'İlaç & Sağlık', 158.50],
  ['JNPR_US', 'Juniper AI Networks', 'Ağ Altyapısı', 38.20],
  ['JPM_US', 'JPMorgan Chase Bank', 'Bankacılık & Finans', 248.50],
  ['K_US', 'Kellanova Snacks', 'Atıştırmalık Gıda', 81.20],
  ['KDP_US', 'Keurig Dr Pepper Beverages', 'Kahve & İçecekler', 34.20],
  ['KEY_US', 'KeyCorp Banking', 'Ticari Bankacılık', 18.60],
  ['KEYS_US', 'Keysight Test Systems', 'Elektronik Test Ekipmanı', 162.50],
  ['KIM', 'Kimco Realty Corporation', 'Açık Hava Alışveriş Merkezleri GYO', 23.50],
  ['KKR', 'KKR & Co. Inc.', 'Özel Sermaye (Private Equity) & Varlık', 152.00],
  ['KLAC_US', 'KLA Semiconductor Inspection', 'Yarı İletken Denetim', 665.50],
  ['KMB_US', 'Kimberly-Clark Hygiene', 'Kişisel Bakım', 138.50],
  ['KMI_US', 'Kinder Morgan Pipeline', 'Enerji Boru Hatları', 26.60],
  ['KMX', 'CarMax Inc.', 'İkinci El Otomobil Perakende Lideri', 78.00],
  ['KO_US', 'Coca-Cola Beverage', 'Meşrubat Sanayi', 64.60],
  ['KR_US', 'Kroger Supermarkets', 'Perakende Market', 58.20],
  ['L', 'Loews Corporation', 'Mülk Sigortası & Enerji Taşımacılığı', 84.00],
  ['LDOS', 'Leidos Holdings Inc.', 'Savunma, İstihbarat & Bilişim', 178.00],
  ['LEN', 'Lennar Corporation', 'Konut Geliştirme & İnşaat', 168.00],
  ['LH', 'Laboratory Corp. of America (LabCorp)', 'Klinik Laboratuvar & Tanı Hizmetleri', 235.00],
  ['LHX', 'L3Harris Technologies Inc.', 'Savunma Elektroniği, İletişim & C4ISR', 248.00],
  ['LIN_US', 'Linde Industrial Gas', 'Endüstriyel Gazlar', 455.50],
  ['LKQ', 'LKQ Corporation', 'Geri Dönüşümlü & Yan Sanayi Oto Parçası', 38.00],
  ['LLY_US', 'Eli Lilly Pharma', 'İlaç & Biyoteknoloji', 785.50],
  ['LNT', 'Alliant Energy Corporation', 'Elektrik & Doğalgaz Kamu Hizmeti', 61.00],
  ['LRCX_US', 'Lam Research Semiconductor', 'Çip Üretim Ekipmanı', 78.60],
  ['LULU_US', 'Lululemon Athletic Apparel', 'Spor Giyim & Moda', 345.50],
  ['LUV_US', 'Southwest Airlines Flight', 'Havacılık', 32.20],
  ['LVS_US', 'Las Vegas Sands Casino', 'Casino & Konaklama', 54.20],
  ['LW', 'Lamb Weston Holdings Inc.', 'Dondurulmuş Patates Ürünleri', 78.00],
  ['LYB', 'LyondellBasell Industries N.V.', 'Plastik, Kimyasallar & Polimerler', 88.00],
  ['LYV', 'Live Nation Entertainment Inc.', 'Canlı Müzik Konserleri & Ticketmaster', 128.00]
];

// Deduplicate US items by symbol
const uniqueUsMap = new Map();
usStocksRaw.forEach(([symbol, name, sector, basePrice]) => {
  if (!uniqueUsMap.has(symbol)) {
    uniqueUsMap.set(symbol, {
      symbol,
      name,
      exchange: 'NASDAQ/NYSE',
      category: 'US_STOCKS',
      currency: '$',
      yahooTicker: symbol.replace('_US', ''),
      sector,
      basePrice
    });
  }
});

const finalUs = Array.from(uniqueUsMap.values());
console.log('Final US count:', finalUs.length);

const usFile = `export interface StockDefinition {
  symbol: string;
  name: string;
  exchange: string;
  category: 'US_STOCKS';
  currency: '$';
  yahooTicker: string;
  sector: string;
  basePrice: number;
}

// ABD S&P 500 & NASDAQ 100 En Büyük 500+ Şirket Listesi
export const US_500_STOCKS: StockDefinition[] = ${JSON.stringify(finalUs, null, 2)};
`;
fs.writeFileSync('./server/data/usUniverse.ts', usFile, 'utf8');

console.log('Successfully generated server/data/usUniverse.ts with', finalUs.length, 'companies.');
