const fs = require('fs');

// ==========================================
// 1. GENERATE BIST 300+ COMPANIES
// ==========================================
const bistData = [
  // BIST 30 & Large-Cap Heavyweights
  ['THYAO', 'Türk Hava Yolları', 'Havacılık', 308.50],
  ['ASELS', 'Aselsan Savunma Sanayi', 'Savunma Sanayi', 72.80],
  ['TUPRS', 'Tüpraş Petrol Rafinerileri', 'Enerji & Petrol', 154.60],
  ['KCHOL', 'Koç Holding', 'Holding', 202.40],
  ['EREGL', 'Ereğli Demir Çelik', 'Demir Çelik', 49.60],
  ['BIMAS', 'BİM Birleşik Mağazalar', 'Perakende', 486.00],
  ['SISE', 'Şişecam Cam Sanayii', 'Cam & Sanayi', 47.30],
  ['AKBNK', 'Akbank T.A.Ş.', 'Bankacılık', 58.90],
  ['GARAN', 'Garanti BBVA', 'Bankacılık', 114.80],
  ['YKBNK', 'Yapı ve Kredi Bankası', 'Bankacılık', 32.90],
  ['ISCTR', 'Türkiye İş Bankası (C)', 'Bankacılık', 14.75],
  ['SAHOL', 'Sabancı Holding', 'Holding', 94.50],
  ['FROTO', 'Ford Otomotiv Sanayi', 'Otomotiv', 1130.00],
  ['PGSUS', 'Pegasus Hava Taşımacılığı', 'Havacılık', 239.00],
  ['TOASO', 'Tofaş Türk Otomobil Fabrikası', 'Otomotiv', 245.00],
  ['TCELL', 'Turkcell İletişim Hizmetleri', 'Telekomünikasyon', 98.40],
  ['TTKOM', 'Türk Telekomünikasyon', 'Telekomünikasyon', 52.60],
  ['ENKAI', 'Enka İnşaat ve Sanayi', 'İnşaat & Taahhüt', 46.80],
  ['EKGYO', 'Emlak Konut Gayrimenkul Yatırım', 'Gayrimenkul', 11.85],
  ['PETKM', 'Petkim Petrokimya Holding', 'Kimya & Petrokimya', 21.40],
  ['ASTOR', 'Astor Enerji A.Ş.', 'Enerji & Ekipman', 96.20],
  ['KONTG', 'Kontrolmatik Teknoloji Enerji', 'Teknoloji & Enerji', 58.40],
  ['SASA', 'SASA Polyester Sanayi', 'Kimya & Tekstil', 4.85],
  ['HEKTS', 'Hektaş Ticaret T.A.Ş.', 'Tarım & Kimya', 3.95],
  ['CCOLA', 'Coca-Cola İçecek A.Ş.', 'Gıda & İçecek', 68.50],
  ['MGROS', 'Migros Ticaret A.Ş.', 'Perakende', 512.00],
  ['KOZAL', 'Koza Altın İşletmeleri', 'Madencilik', 23.40],
  ['KOZAA', 'Koza Anadolu Metal Madencilik', 'Madencilik', 62.50],
  ['IPEKE', 'İpek Doğal Enerji Kaynakları', 'Madencilik & Enerji', 44.80],
  ['ALARK', 'Alarko Holding', 'Holding & Enerji', 104.20],
  ['ARCLK', 'Arçelik A.Ş.', 'Dayanıklı Tüketim', 162.00],
  ['VESTL', 'Vestel Elektronik Sanayi', 'Elektronik & Tüketim', 78.40],
  ['VESBE', 'Vestel Beyaz Eşya Sanayi', 'Dayanıklı Tüketim', 21.60],
  ['OYAKC', 'OYAK Çimento Fabrikaları', 'Çimento & Yapı', 68.30],
  ['CIMSA', 'Çimsa Çimento Sanayi', 'Çimento & Yapı', 35.80],
  ['AKCNS', 'Akçansa Çimento Sanayi', 'Çimento & Yapı', 158.00],
  ['SOKM', 'Şok Marketler Ticaret', 'Perakende', 51.50],
  ['BIZIM', 'Bizim Toptan Satış Mağazaları', 'Perakende', 39.20],
  ['TAVHL', 'TAV Havalimanları Holding', 'Havacılık & Liman', 242.00],
  ['CLEBI', 'Çelebi Hava Servisi', 'Havacılık Hizmetleri', 1840.00],
  ['GUBRF', 'Gübre Fabrikaları T.A.Ş.', 'Tarım & Gübre', 178.00],
  ['BAGFS', 'Bağfaş Bandırma Gübre Fabrikaları', 'Tarım & Gübre', 28.50],
  ['EGEEN', 'Ege Endüstri ve Ticaret', 'Otomotiv Yan Sanayi', 12450.00],
  ['BRISA', 'Brisa Bridgestone Lastik Sanayi', 'Otomotiv & Lastik', 118.00],
  ['GOODY', 'Goodyear Lastikleri T.A.Ş.', 'Otomotiv & Lastik', 22.40],
  ['OTKAR', 'Otokar Otomotiv ve Savunma', 'Otomotiv & Savunma', 525.00],
  ['DOAS', 'Doğuş Otomotiv Servis', 'Otomotiv & Dağıtım', 284.00],
  ['TMSN', 'Tümosan Motor ve Traktör', 'Otomotiv & Makine', 126.00],
  ['KARSN', 'Karsan Otomotiv Sanayii', 'Otomotiv & Ulaşım', 12.80],
  ['ASUZU', 'Anadolu Isuzu Otomotiv', 'Otomotiv & Ticari Araç', 212.00],
  ['KRDMD', 'Kardemir Karabük Demir Çelik (D)', 'Demir Çelik', 27.80],
  ['KRDMA', 'Kardemir Karabük Demir Çelik (A)', 'Demir Çelik', 25.40],
  ['KRDMB', 'Kardemir Karabük Demir Çelik (B)', 'Demir Çelik', 24.60],
  ['CEMTS', 'Çemtaş Çelik Makina Sanayi', 'Demir Çelik & Makine', 11.90],
  ['BUCIM', 'Bursa Çimento Fabrikası', 'Çimento & Yapı', 8.45],
  ['NUHCM', 'Nuh Çimento Sanayi', 'Çimento & Yapı', 315.00],
  ['AFYON', 'Afyon Çimento Sanayi', 'Çimento & Yapı', 13.80],
  ['BTCIM', 'Batıçim Batı Anadolu Çimento', 'Çimento & Yapı', 142.00],
  ['CANTE', 'Çan2 Termik A.Ş.', 'Enerji & Üretim', 16.50],
  ['ODAS', 'Odaş Elektrik Üretim', 'Enerji & Madencilik', 7.95],
  ['AKSEN', 'Aksa Enerji Üretim', 'Enerji & Üretim', 41.60],
  ['ZOREN', 'Zorlu Enerji Elektrik Üretim', 'Enerji & Yenilenebilir', 4.85],
  ['GWIND', 'Galata Wind Enerji A.Ş.', 'Yenilenebilir Enerji', 28.90],
  ['ENJSA', 'Enerjisa Enerji A.Ş.', 'Enerji Dağıtım', 63.40],
  ['AKENR', 'Akenerji Elektrik Üretim', 'Enerji & Üretim', 17.20],
  ['CWENE', 'CW Enerji Mühendislik', 'Güneş Enerjisi & Teknoloji', 210.00],
  ['EUPWR', 'Europower Enerji ve Otomasyon', 'Elektrik & Otomasyon', 92.50],
  ['ALFAS', 'Alfa Solar Enerji Sanayi', 'Güneş Enerjisi', 74.80],
  ['KOPOL', 'Koza Polyester Sanayi', 'Kimya & Tekstil', 42.50],
  ['SDTTR', 'SDT Uzay ve Savunma Teknolojileri', 'Savunma & Uzay', 285.00],
  ['MIATK', 'Mia Teknoloji A.Ş.', 'Yazılım & Bilişim', 58.20],
  ['REEDR', 'Reeder Teknoloji Sanayi', 'Elektronik & Teknoloji', 23.90],
  ['VBTYZ', 'VBT Yazılım A.Ş.', 'Yazılım & Bilişim', 38.60],
  ['ARDYZ', 'Ard Grup Bilişim Teknolojileri', 'Bilişim Teknolojileri', 46.20],
  ['PAPIL', 'Papilon Savunma Güvenlik', 'Biyometri & Savunma', 94.00],
  ['AGESA', 'Agesa Hayat ve Emeklilik', 'Sigortacılık', 118.00],
  ['ANSGR', 'Anadolu Anonim Türk Sigorta', 'Sigortacılık', 96.50],
  ['AKGRT', 'Aksigorta A.Ş.', 'Sigortacılık', 8.20],
  ['TURSG', 'Türkiye Sigorta A.Ş.', 'Sigortacılık', 64.00],
  ['ANHYT', 'Anadolu Hayat Emeklilik', 'Sigortacılık', 98.00],
  ['ISGYO', 'İş Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul', 16.40],
  ['TRGYO', 'Torunlar Gayrimenkul Yatırım', 'Gayrimenkul', 48.60],
  ['OZKGY', 'Özak Gayrimenkul Yatırım', 'Gayrimenkul', 10.20],
  ['DGGYO', 'Doğuş Gayrimenkul Yatırım', 'Gayrimenkul', 52.00],
  ['SNGYO', 'Sinpaş Gayrimenkul Yatırım', 'Gayrimenkul', 4.60],
  ['KLGYO', 'Kiler Gayrimenkul Yatırım', 'Gayrimenkul', 4.90],
  ['HLGYO', 'Halk Gayrimenkul Yatırım', 'Gayrimenkul', 5.40],
  ['VAKKO', 'Vakko Tekstil ve Hazır Giyim', 'Tekstil & Lüks Giyim', 94.00],
  ['MAVI', 'Mavi Giyim Sanayi ve Ticaret', 'Tekstil & Moda', 92.50],
  ['YATAS', 'Yataş Yatak ve Yorgan Sanayi', 'Mobilya & Tekstil', 34.80],
  ['DESA', 'Desa Deri Sanayi ve Ticaret', 'Deri & Moda', 21.40],
  ['DERIM', 'Derimod Konfeksiyon Ayakkabı', 'Deri & Ayakkabı', 36.80],
  ['BRKO', 'Birko Birleşik Koyunlular Mensucat', 'Tekstil', 7.40],
  ['SKBNK', 'Şekerbank T.A.Ş.', 'Bankacılık', 4.95],
  ['TSKB', 'Türkiye Sınai Kalkınma Bankası', 'Bankacılık', 12.80],
  ['ALBRK', 'Albaraka Türk Katılım Bankası', 'Katılım Bankacılığı', 5.85],
  ['SELEC', 'Selçuk Ecza Deposu Ticaret', 'İlaç Dağıtım', 64.50],
  ['LOGO', 'Logo Yazılım Sanayi ve Ticaret', 'Kurumsal Yazılım', 96.00],
  ['NETAS', 'Netaş Telekomünikasyon', 'Telekom Altyapı', 72.00],
  ['INDES', 'İndeks Bilgisayar Sistemleri', 'Bilişim Dağıtım', 8.90],
  ['ARENA', 'Arena Bilgisayar Sanayi', 'Bilişim Dağıtım', 42.00],
  ['DGATE', 'Datagate Bilgisayar Malzemeleri', 'Bilişim Ekipmanları', 39.50],
  ['PKART', 'Plastikkart Akıllı Kart İletişim', 'Akıllı Kart Teknolojileri', 124.00],
  ['LINK', 'Link Bilgisayar Sistemleri', 'Yazılım & ERP', 485.00],
  ['DESPC', 'Despec Bilgisayar Pazarlama', 'Bilişim Sarf Malzemeleri', 41.50],
  ['FONET', 'Fonet Bilgi Teknolojileri', 'Sağlık Bilişimi', 26.80],
  ['SMART', 'Smartiks Yazılım A.Ş.', 'Yazılım & Veri', 64.00],
  ['MOBTL', 'Mobiltel İletişim Hizmetleri', 'Telekom Dağıtım', 4.40],
  ['KRONT', 'Kron Telekomünikasyon', 'Siber Güvenlik & Ağ', 26.50],
  ['FORTE', 'Forte Bilgi İletişim Teknolojileri', 'Savunma Bilişim', 68.00],
  ['TABGD', 'TAB Gıda Sanayi ve Ticaret', 'Hızlı Servis Restoran', 148.00],
  ['OBAMS', 'Oba Makarnacılık Sanayi', 'Gıda Sanayi', 37.80],
  ['TATGD', 'Tat Gıda Sanayi A.Ş.', 'Gıda & Konserve', 26.40],
  ['ULUUN', 'Ulusoy Un Sanayi ve Ticaret', 'Gıda & Un Sanayi', 28.50],
  ['TUKAS', 'Tukaş Gıda Sanayi ve Ticaret', 'Gıda Sanayi', 7.45],
  ['BANVT', 'Banvit Bandırma Vitaminli Yem', 'Gıda & Kanatlı', 380.00],
  ['DARDL', 'Dardanel Önentaş Gıda Sanayi', 'Gıda & Su Ürünleri', 5.60],
  ['SELVA', 'Selva Gıda Sanayi A.Ş.', 'Gıda Ürünleri', 14.80],
  ['PETUN', 'Pınar Entegre Et ve Un', 'Gıda & Et Ürünleri', 94.00],
  ['PNSUT', 'Pınar Süt Mamülleri Sanayii', 'Gıda & Süt Ürünleri', 86.50],
  ['PINSU', 'Pınar Su ve İçecek Sanayi', 'Gıda & İçecek', 22.80],
  ['AEFES', 'Anadolu Efes Biracılık ve Malt', 'İçecek Sanayi', 198.00],
  ['TBORG', 'Türk Tuborg Bira ve Malt', 'İçecek Sanayi', 112.00],
  ['YYLGD', 'Yayla Agro Gıda Sanayi', 'Gıda & Bakliyat', 13.60],
  ['GOKNR', 'Göknur Gıda Maddeleri Enerji', 'Meyve Suyu Sanayi', 28.40],
  ['KAYSE', 'Kayseri Şeker Fabrikası', 'Şeker Sanayi', 29.50],
  ['MEKAG', 'Meka Beton Santralleri İmalat', 'Makine İmalatı', 64.00],
  ['ENERY', 'Enerya Enerji A.Ş.', 'Doğalgaz Dağıtım', 184.00],
  ['AHGAZ', 'Ahlatcı Doğal Gaz Dağıtım', 'Doğalgaz & Finans', 14.20],
  ['MANAS', 'Manas Enerji Yönetimi', 'Enerji Sayaç & Yönetim', 11.20],
  ['SAYAS', 'Say Yenilenebilir Enerji', 'Rüzgar & Güneş Ekipman', 72.00],
  ['YEOTK', 'YEO Teknoloji Enerji', 'Enerji Mühendislik & Otomasyon', 196.00],
  ['BIOEN', 'Biotrend Çevre ve Enerji', 'Biyokütle Enerji', 18.90],
  ['CONSE', 'Consus Enerji İşletmeciliği', 'Biyokütle & Güneş', 6.80],
  ['HUNER', 'Hun Yenilenebilir Enerji', 'Yenilenebilir Enerji', 4.90],
  ['MAGEN', 'Margün Trend Enerji Yatırım', 'Güneş Santralleri', 12.80],
  ['ESEN', 'Esenboğa Elektrik Üretim', 'Güneş Enerjisi', 22.40],
  ['NATEN', 'Naturel Yenilenebilir Enerji', 'Güneş Yatırımları', 54.00],
  ['PAMEL', 'Pamel Yenilenebilir Elektrik', 'Hidroelektrik Santral', 142.00],
  ['AYDEM', 'Aydem Yenilenebilir Enerji', 'Yenilenebilir Enerji', 24.60],
  ['KAREL', 'Karel Elektronik Sanayi', 'Elektronik & Telekom', 14.80],
  ['ESCOM', 'Escort Teknoloji Yatırım', 'Bilişim Yatırımları', 44.00],
  ['KFEIN', 'Kafein Yazılım Hizmetleri', 'Yazılım Hizmetleri', 114.00],
  ['TMPOL', 'Temapol Polimer Plastik', 'Plastik & Polimer', 84.00],
  ['BRMEN', 'Birlik Mensucat Ticaret', 'Tekstil & Dokuma', 7.10],
  ['BRKSN', 'Berkosan Yalıtım ve Tecrit', 'Yalıtım & İzolasyon', 34.50],
  ['BRSAN', 'Borusan Birleşik Boru', 'Çelik Boru Sanayi', 580.00],
  ['ERBOS', 'Erbosan Erciyas Boru Sanayii', 'Çelik Boru İmalat', 192.00],
  ['BMSCH', 'BMS Çelik Hasır Sanayi', 'Çelik Hasır', 22.40],
  ['TUCLK', 'Tuğçelik Alüminyum ve Metal', 'Alüminyum Metal', 14.20],
  ['DMSAS', 'Demisaş Döküm Emaye', 'Otomotiv Döküm', 10.80],
  ['SARKY', 'Sarkuysan Elektrolitik Bakır', 'Bakır & Tel Sanayi', 34.20],
  ['CELHA', 'Çelik Halat ve Tel Sanayii', 'Çelik Halat & Tel', 42.00],
  ['PARSN', 'Parsan Ezme Çelik Dövme', 'Otomotiv Dövme Çelik', 124.00],
  ['JANTS', 'Jantsa Jant Sanayi', 'Otomotiv Jant Sanayi', 32.50],
  ['DITAS', 'Ditaş Doğan Yedek Parça', 'Otomotiv Yedek Parça', 28.00],
  ['MAKTK', 'Makina Takım Endüstrisi', 'Kesici Takım & Makine', 8.90],
  ['KLMSN', 'Klimasan Klima Sanayi', 'Soğutma Sistemleri', 28.40],
  ['EGSER', 'Ege Seramik Sanayi', 'Seramik & Karo', 6.80],
  ['QUAGR', 'Qua Granite Hayal Yapı', 'Granit & Seramik', 3.40],
  ['BIENY', 'Bien Yapı Ürünleri Sanayi', 'Yapı Malzemeleri & Seramik', 34.00],
  ['KMPUR', 'Kimteks Poliüretan Sanayi', 'Poliüretan Sistemleri', 24.80],
  ['INVES', 'Investco Holding A.Ş.', 'Girişim Sermayesi', 340.00],
  ['GENIL', 'Gen İlaç ve Sağlık Ürünleri', 'İlaç & Biyoteknoloji', 78.50],
  ['TRILC', 'Türk İlaç ve Serum Sanayi', 'İlaç & Aşı Üretimi', 23.40],
  ['ONCSM', 'Oncosem Onkolojik Sistemler', 'Tıbbi Cihaz & Onkoloji', 186.00],
  ['RNPOL', 'Rainbow Polikarbonat Sanayi', 'Plastik Polikarbonat', 28.90],
  ['POLHO', 'Polisan Holding A.Ş.', 'Boya, Kimya & Liman', 14.80],
  ['DYOBY', 'Dyo Boya Fabrikaları', 'Boya & Kaplama', 42.50],
  ['MRSHL', 'Marshall Boya ve Vernik', 'Boya Sanayi', 2140.00],
  ['DEVA', 'Deva Holding A.Ş.', 'İlaç Üretimi', 84.00],
  ['RTALB', 'RTA Laboratuvarları Biyolojik', 'Biyolojik Tanı Ürünleri', 14.20],
  ['ECZYT', 'Eczacıbaşı Yatırım Holding', 'Holding & Yatırım', 275.00],
  ['ECILC', 'Eczacıbaşı İlaç Sınai Finansal', 'İlaç & Sağlık', 54.00],
  ['KARTN', 'Kartonsan Karton Sanayi', 'Karton & Ambalaj', 114.00],
  ['ALKIM', 'Alkim Alkali Kimya A.Ş.', 'Kimya Sanayi', 32.80],
  ['ALKA', 'Alkim Kağıt Sanayi', 'Kağıt Sanayii', 27.50],
  ['BAKAB', 'Bak Ambalaj Sanayi', 'Ambalaj Sanayi', 48.00],
  ['GEDZA', 'Gediz Ambalaj Sanayi', 'Oluklu Plastik Kutu', 38.40],
  ['PRKAB', 'Türk Prysmian Kablo', 'Kablo & İletişim Sistemleri', 36.20],
  ['OZSUB', 'Özsu Balık Üretimi', 'Su Ürünleri', 24.50],
  ['SMRTG', 'Smart Güneş Enerjisi Teknoloji', 'Güneş Panelleri', 48.20],
  ['CVKMD', 'CVK Maden İşletmeleri', 'Maden İşletmeciliği', 460.00],
  ['KZBGY', 'Kuzugrup Gayrimenkul Yatırım', 'Gayrimenkul', 28.50],
  ['KZGYO', 'Kuzey Boru A.Ş.', 'Boru Sistemleri', 118.00],
  ['SURGY', 'Sur Tatil Evleri GYO', 'Turizm & GYO', 46.00],
  ['DMRGD', 'DMR Unlu Mamuller', 'Gıda & Unlu Mamul', 16.80],
  ['BSOKE', 'Batısöke Söke Çimento', 'Çimento Sanayi', 38.00],
  ['BASGZ', 'Başkent Doğalgaz Dağıtım', 'Doğalgaz & Altyapı', 19.50],
  ['BEYAZ', 'Beyaz Filo Oto Kiralama', 'Filo Kiralama', 24.00],
  ['BVSAN', 'Bülbüloğlu Vinç Sanayi', 'Endüstriyel Vinç', 98.00],
  ['CEMAS', 'Çemaş Döküm Sanayi', 'Döküm & Taşlama', 4.90],
  ['CMBTN', 'Çimbeton Hazırbeton', 'Hazır Beton', 2650.00],
  ['CRFSA', 'CarrefourSA Sabancı', 'Perakende & Market', 128.00],
  ['CUSAN', 'Çuhadaroğlu Metal Sanayi', 'Alüminyum Metal', 22.00],
  ['DERHL', 'Derlüks Yatırım Holding', 'Holding & Yatırım', 14.50],
  ['DNISI', 'Dinamik Isı Makina', 'Yalıtım & İzolasyon', 11.80],
  ['DOGUB', 'Doğusan Boru Sanayi', 'Boru Sanayi', 12.40],
  ['DOCO', 'DO & CO Aktiengesellschaft', 'İkram Hizmetleri', 5940.00],
  ['EDATA', 'E-Data Teknoloji Pazarlama', 'Siber Güvenlik Dağıtım', 21.60],
  ['EGGUB', 'Ege Gübre Sanayii', 'Gübre & Liman', 56.50],
  ['EGPRO', 'Ege Profil Ticaret Sanayi', 'PVC Profil', 214.00],
  ['EMKEL', 'Emek Elektrik Endüstrisi', 'Elektrik İmalatı', 38.50],
  ['EPLAS', 'Egeplast Ege Plastik', 'Plastik Boru', 9.80],
  ['ERSU', 'Ersu Meyve Suları', 'Meyve Suyu', 7.80],
  ['ESCAR', 'Escar Turizm Taşımacılık', 'Filo Kiralama', 248.00],
  ['ETILR', 'Etiler Gıda Ticari Yatırımlar', 'Restoran Zinciri', 24.00],
  ['EYGYO', 'EYG Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 8.90],
  ['FADE', 'Fade Gıda Yatırım Sanayi', 'Gıda Ürünleri', 14.50],
  ['FMIZP', 'Federal-Mogul İzmit Piston', 'Piston & Motor Parça', 285.00],
  ['FORMT', 'Formet Metal ve Cam', 'Metal Eşya', 3.60],
  ['FRIGO', 'Frigo-Pak Gıda Maddeleri', 'Konserve Gıda', 7.40],
  ['FZLGY', 'Fuzul Gayrimenkul Yatırım', 'Gayrimenkul', 16.80],
  ['GEDIK', 'Gedik Yatırım Menkul', 'Aracı Kurum', 14.20],
  ['GENTS', 'Gentaş Dekoratif Yüzeyler', 'Laminat & Yapı', 8.90],
  ['GEREL', 'Gersan Elektrik Ticaret', 'Elektrik Sistemleri', 32.00],
  ['GLBMD', 'Global Menkul Değerler', 'Aracı Kurum', 68.00],
  ['GLCVY', 'Gelecek Varlık Yönetimi', 'Varlık Yönetimi', 38.40],
  ['GLRYH', 'Güler Yatırım Holding', 'Yatırım Holding', 12.90],
  ['GLYHO', 'Global Yatırım Holding', 'Liman & Enerji', 14.60],
  ['GOZDE', 'Gözde Girişim Sermayesi', 'Girişim Sermayesi', 28.50],
  ['GSDDE', 'GSD Denizcilik Gayrimenkul', 'Deniz Taşımacılığı', 11.20],
  ['GSDHO', 'GSD Holding A.Ş.', 'Denizcilik & Finans', 4.40],
  ['GZNMI', 'Gezinomi Seyahat Turizm', 'Online Seyahat', 48.00],
  ['HALKB', 'Türkiye Halk Bankası', 'Bankacılık', 16.80],
  ['HATEK', 'Hateks Hatay Tekstil', 'İplik & Dokuma', 14.60],
  ['HDFGS', 'Hedef Girişim Sermayesi', 'Girişim Sermayesi', 2.80],
  ['HEDEF', 'Hedef Holding A.Ş.', 'Finans & Teknoloji', 26.50],
  ['HUBVC', 'Hub Girişim Sermayesi', 'Teknoloji Girişim', 8.40],
  ['ICBCT', 'ICBC Turkey Bank', 'Ticari Bankacılık', 12.60],
  ['IEYHO', 'Işıklar Enerji Yapı Holding', 'Enerji & Ambalaj', 4.20],
  ['IHEVA', 'İhlas Ev Aletleri', 'Ev Aletleri İmalatı', 3.80],
  ['IHGZV', 'İhlas Gazetecilik', 'Medya Hizmetleri', 3.40],
  ['IHLAS', 'İhlas Holding A.Ş.', 'Holding Hizmetleri', 1.45],
  ['IHLGM', 'İhlas Gayrimenkul Proje', 'İnşaat Projeleri', 1.85],
  ['IHMAD', 'İhlas Madencilik Enerji', 'Madencilik', 11.20],
  ['IMASM', 'İmaş Makina Sanayi', 'Makine İmalatı', 16.50],
  ['INFO', 'İnfo Yatırım Menkul', 'Aracı Kurum', 13.80],
  ['ISBIR', 'İşbir Holding A.Ş.', 'Sünger & Sentetik', 184.00],
  ['ISDMR', 'İskenderun Demir ve Çelik', 'Demir Çelik Sanayi', 39.40],
  ['ISFIN', 'İş Finansal Kiralama', 'Finansal Kiralama', 14.20],
  ['ISGSY', 'İş Girişim Sermayesi', 'Girişim Sermayesi', 24.00],
  ['ISKPL', 'Işık Plastik Sanayi', 'Plastik Levha', 8.80],
  ['ISMEN', 'İş Yatırım Menkul Değerler', 'Yatırım Bankacılığı', 34.60],
  ['ISSEN', 'İşbir Sentetik Dokuma', 'Sentetik Dokuma', 12.80],
  ['ISYAT', 'İş Yatırım Ortaklığı', 'Yatırım Ortaklığı', 9.60],
  ['ITTFH', 'İttifak Holding', 'Holding', 3.60],
  ['IZMDC', 'İzmir Demir Çelik', 'Demir Çelik', 6.40],
  ['KAPLM', 'Kaplamin Ambalaj Sanayi', 'Ambalaj & Kutu', 142.00],
  ['KARYA', 'Kartal Yenilenebilir Enerji', 'Güneş Enerjisi', 28.00],
  ['KATMR', 'Katmerciler Araç Üstü Ekipman', 'Savunma Araçları', 2.45],
  ['KCAER', 'Kocaer Çelik Sanayi', 'Çelik Profil', 48.00],
  ['KERVT', 'Kerevitaş Gıda Sanayi', 'Dondurulmuş Gıda', 14.80],
  ['KIMMR', 'Ersin Kim Market', 'Market Zinciri', 8.20],
  ['KLNMA', 'Kalkınma ve Yatırım Bankası', 'Kalkınma Bankacılığı', 34.00],
  ['KLRHO', 'Kiler Holding A.Ş.', 'Holding', 38.00],
  ['KNFRT', 'Konfrut Tarım A.Ş.', 'Meyve Konsantre', 11.40],
  ['KONKA', 'Konya Kağıt Sanayi', 'Kağıt İmalatı', 49.00],
  ['KONYA', 'Konya Çimento Sanayii', 'Çimento Sanayi', 11200.00],
  ['KORDS', 'Kordsa Teknik Tekstil', 'Kompozit & Lastik', 94.00],
  ['KRGYO', 'Körfez Gayrimenkul Yatırım', 'Gayrimenkul', 28.00],
  ['KRPLS', 'Koroplast Temizlik Ambalaj', 'Temizlik & Ambalaj', 9.20],
  ['KRSTL', 'Kristal Kola ve Meşrubat', 'İçecek Sanayi', 9.80],
  ['KRTEK', 'Karsu Tekstil Sanayii', 'İplik Sanayi', 24.00],
  ['KRVGD', 'Kervan Gıda Sanayi', 'Şekerleme Sanayi', 2.65],
  ['KSTUR', 'Kuştur Kuşadası Turizm', 'Otelcilik', 5600.00],
  ['KTLEV', 'Katılımevim Tasarruf Finans', 'Tasarruf Finansman', 68.00],
  ['KTSKR', 'Kütahya Şeker Fabrikası', 'Şeker Sanayi', 58.00],
  ['KUTPO', 'Kütahya Porselen Sanayi', 'Porselen Ürünleri', 74.00],
  ['KUVVA', 'Kuvva Gıda Ticaret', 'Gıda Ticareti', 46.00],
  ['KUYAS', 'Kuvva Kuyumcukent Gayrimenkul', 'Gayrimenkul Projeleri', 54.00],
  ['LIDER', 'Lider Filo Kiralama', 'Filo Kiralama', 68.00],
  ['LILAK', 'Lila Kağıt Sanayi', 'Temizlik Kağıdı', 26.50],
  ['LKMNH', 'Lokman Hekim Engürüsağ', 'Özel Hastane', 18.20],
  ['LUKSK', 'Lüks Kadife Ticaret Sanayi', 'Kadife Kumaş', 68.00],
  ['MAALT', 'Marmaris Altınyunus Turistik', 'Turizm & Otel', 980.00],
  ['MACKO', 'Maçkolik İnternet Hizmetleri', 'Spor Medyası', 94.00],
  ['MAKIM', 'Makim Makina Teknolojileri', 'Hassas Döküm', 42.00],
  ['MARBL', 'Tureks Turunç Madencilik', 'Doğaltaş & Mermer', 14.80],
  ['MARKA', 'Marka Yatırım Holding', 'Yatırım Holding', 84.00],
  ['MARTI', 'Martı Otel İşletmeleri', 'Otelcilik', 4.80],
  ['MEDTR', 'Meditera Tıbbi Malzeme', 'Tıbbi Malzemeler', 38.00],
  ['MEGAP', 'Mega Polietilen Köpük', 'Polietilen Köpük', 4.90],
  ['MEGSP', 'Mega Metal Sanayi Ticaret', 'Bakır Tel Sanayi', 42.00],
  ['MENGD', 'MNG Havayolları Kargo', 'Kargo Taşımacılığı', 86.00],
  ['MERCN', 'Mercan Kimya Sanayi', 'Kimya Sanayi', 12.80],
  ['MERIT', 'Merit Turizm Yatırımları', 'Turizm & Otelcilik', 128.00],
  ['MERKO', 'Merko Gıda Sanayi', 'Salça & Konserve', 9.40],
  ['METRO', 'Metro Ticari Mali Yatırımlar', 'Ulaşım & Turizm', 2.80],
  ['METUR', 'Metemtur Otelcilik', 'Turizm & Otel', 14.20],
  ['MHRGY', 'MHR Gayrimenkul Yatırım', 'Gayrimenkul', 4.90],
  ['MNDRS', 'Menderes Tekstil Sanayi', 'Ev Tekstili', 9.80],
  ['MNDTR', 'Mondi Turkey Oluklu Mukavva', 'Mukavva & Ambalaj', 16.50],
  ['MOGAN', 'Mogan Enerji Yatırım Holding', 'Yenilenebilir Enerji', 12.80],
  ['MPARK', 'MLP Sağlık Hizmetleri', 'Özel Hastane Zinciri', 342.00],
  ['MRGYO', 'Martı Gayrimenkul Yatırım', 'Gayrimenkul', 7.40],
  ['MSGYO', 'Mistral Gayrimenkul Yatırım', 'Gayrimenkul', 8.20],
  ['MTRKS', 'Matriks Bilgi Dağıtım', 'Finansal Veri', 54.00],
  ['MTRYO', 'Metro Yatırım Ortaklığı', 'Portföy Yönetimi', 7.80],
  ['NIBAS', 'Niğde Beton Sanayi', 'Prefabrik Beton', 18.50],
  ['NTHOL', 'Net Holding A.Ş.', 'Turizm & Şans Oyunları', 46.00],
  ['NUGYO', 'Nurol Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 4.80],
  ['OASIS', 'Oasis Rezidans GYO', 'Gayrimenkul', 14.50],
  ['OFSYM', 'Ofis Yem Gıda Sanayi', 'Hayvan Yemi Sanayi', 48.00],
  ['ORGE', 'Orge Enerji Elektrik Taahhüt', 'Elektrik Taahhüt', 78.00],
  ['ORMA', 'Orma Orman Mamulleri', 'Orman Ürünleri', 168.00],
  ['OSMEN', 'Osmanlı Yatırım Menkul', 'Aracı Kurum', 186.00],
  ['OSTIM', 'Ostim Endüstriyel Yatırımlar', 'Sanayi Yatırımları', 8.40],
  ['OYAYO', 'Oyak Yatırım Ortaklığı', 'Yatırım Ortaklığı', 34.00],
  ['OYLUM', 'Oylum Sınai Yatırımlar', 'Bisküvi & Gıda', 9.20],
  ['OYYAT', 'Oyak Yatırım Menkul', 'Aracı Kurum', 48.00],
  ['OZGYO', 'Özderici Gayrimenkul Yatırım', 'Gayrimenkul', 5.60],
  ['OZRDN', 'Özerden Plastik Sanayi', 'Ambalaj Ürünleri', 38.00],
  ['PAGYO', 'Panora Gayrimenkul Yatırım', 'AVM & Gayrimenkul', 44.00],
  ['PANVE', 'Panelsan Çatı Cephe', 'Sandviç Panel', 68.00],
  ['PASTV', 'Pasifik Teknoloji Sanayi', 'Teknoloji & Siber Güvenlik', 74.00],
  ['PCILT', 'PC İletişim Medya Sistemleri', 'Medya & Reklam', 16.80],
  ['PEGYO', 'Pera Gayrimenkul Yatırım', 'Gayrimenkul', 8.40],
  ['PEKGY', 'Peker Gayrimenkul Yatırım', 'Gayrimenkul', 28.00],
  ['PENGD', 'Penguen Gıda Sanayi', 'Konserve & Gıda', 7.40],
  ['PENTA', 'Penta Teknoloji Ürünleri', 'Bilişim Dağıtımı', 14.80],
  ['PKENT', 'Petrokent Turizm A.Ş.', 'Tatil Köyü', 198.00],
  ['PLTUR', 'Platform Turizm Taşımacılık', 'Taşımacılık & Servis', 16.50],
  ['PNLSN', 'Panel Sistemleri Çatı', 'Yalıtım Panelleri', 58.00],
  ['POLTK', 'Politeknik Metal Sanayi', 'Metal Kimyasalları', 14200.00],
  ['PRDGS', 'Pardus Girişim Sermayesi', 'Girişim Yatırımları', 6.80],
  ['PRKME', 'Park Elektrik Üretim Maden', 'Madencilik & Enerji', 24.50],
  ['PRZMA', 'Prizma Pres Matbaacılık', 'Matbaacılık', 38.00],
  ['PSDTC', 'Pasifik Donanım ve Yazılım', 'Bilişim Donanım', 64.00],
  ['PSGYO', 'Pasifik Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 7.90],
  ['QNBFB', 'QNB Finansbank A.Ş.', 'Bankacılık Hizmetleri', 285.00],
  ['QNBFL', 'QNB Finans Finansal Kiralama', 'Finansal Kiralama', 142.00],
  ['RALYH', 'Ral Yatırım Holding', 'İnşaat & Enerji', 184.00],
  ['RAYSG', 'Ray Sigorta A.Ş.', 'Sigortacılık', 380.00],
  ['RODRF', 'Rodrigo Tekstil Sanayi', 'Tekstil & Giyim', 84.00],
  ['ROYAL', 'Royal Halı İplik Tekstil', 'Halı Sanayi', 16.50],
  ['RUBNS', 'Rubenis Tekstil Sanayi', 'Tekstil & İplik', 34.00],
  ['RUZGR', 'Rönesans Gayrimenkul Yatırım', 'AVM & GYO', 138.00],
  ['RYGYO', 'Reysaş Gayrimenkul Yatırım', 'Lojistik Depolama', 42.00],
  ['RYSAS', 'Reysaş Taşımacılık Lojistik', 'Lojistik Hizmetleri', 48.00],
  ['SAFKR', 'Safkar Ege Soğutmacılık', 'Klima & Soğutma', 46.00],
  ['SAMAT', 'Saray Matbaacılık Kağıtçılık', 'Matbaacılık & Kağıt', 42.00],
  ['SANEL', 'San-El Mühendislik Elektrik', 'Elektrik Panoları', 24.00],
  ['SANFM', 'Sanifoam Sünger Sanayi', 'Teknik Sünger', 28.00],
  ['SANKO', 'Sanko Pazarlama İthalat', 'Tekstil Pazarlama', 36.00],
  ['SEKFK', 'Şeker Finansal Kiralama', 'Leasing Çözümleri', 16.80],
  ['SEKUR', 'Sekuro Plastik Ambalaj', 'Plastik Ambalaj', 14.50],
  ['SELGD', 'Selçuk Gıda Endüstri', 'Kuru Meyve İhracat', 26.00],
  ['SEYKM', 'Seyitler Kimya Sanayi', 'Tıbbi Malzeme', 9.80],
  ['SILVR', 'Silverline Endüstri Ticaret', 'Ankastre Mutfak', 18.20],
  ['SKTAS', 'Söktaş Tekstil Sanayi', 'Lüks Gömleklik Kumaş', 4.80],
  ['SKYMD', 'Şeker Yatırım Menkul', 'Aracı Kurum', 11.40],
  ['SNDUR', 'Sanica Isı Sanayi (D)', 'Radyatör & Isıtma', 32.00],
  ['SNICA', 'Sanica Isı Sanayi A.Ş.', 'Isıtma Sistemleri', 6.80],
  ['SNKRN', 'Senkron Siber Güvenlik', 'Siber Güvenlik', 38.00],
  ['SOKE', 'Söke Değirmencilik Sanayi', 'Paketli Un Sanayi', 13.80],
  ['SONME', 'Sönmez Filament İplik', 'Sentetik İplik', 74.00],
  ['SRVGY', 'Servet Gayrimenkul Yatırım', 'Gayrimenkul', 480.00],
  ['SUMAS', 'Sumaş Saraylı Mdf Sanayi', 'MDF & Sunta', 490.00],
  ['SUNTK', 'Sun Tekstil Sanayi', 'Hazır Giyim İhracatı', 18.60],
  ['SUWEN', 'Suwen Tekstil Sanayi', 'İç Giyim & Moda', 21.00],
  ['TARKM', 'Tarkim Bitki Koruma', 'Zirai İlaç Üretimi', 580.00],
  ['TATEN', 'Tatlıpınar Enerji Üretim', 'Rüzgar Santralleri', 28.50],
  ['TDGYO', 'Trend Gayrimenkul Yatırım', 'Gayrimenkul', 14.20],
  ['TEKTU', 'Tek-Art Turizm Tesisleri', 'Turizm & Otelcilik', 3.80],
  ['TERA', 'Tera Yatırım Menkul', 'Aracı Kurum', 38.00],
  ['TEZOL', 'Europap Tezol Kağıt', 'Temizlik Kağıtları', 16.40],
  ['TGSAS', 'TGS Dış Ticaret A.Ş.', 'Dış Ticaret Hizmetleri', 26.00],
  ['TKFEN', 'Tekfen Holding A.Ş.', 'Müteahhitlik & Tarım', 74.00],
  ['TKNSA', 'Teknosa İç ve Dış Ticaret', 'Elektronik Perakende', 34.00],
  ['TLMAN', 'Trabzon Liman İşletmeciliği', 'Liman İşletmeciliği', 114.00],
  ['TNZTP', 'Tapdi Oksijen Sağlık', 'Özel Hastanecilik', 8.20],
  ['TRCAS', 'Turcas Petrol A.Ş.', 'Akaryakıt & Enerji', 24.50],
  ['TSPOR', 'Trabzonspor Sportif Yatırım', 'Spor & Futbol', 1.85],
  ['TTRAK', 'Türk Traktör ve Ziraat', 'Traktör İmalatı', 780.00],
  ['TUREX', 'Tureks Turizm Taşımacılık', 'Yolcu Taşımacılığı', 46.00],
  ['TURGG', 'Türker Proje Gayrimenkul', 'Arazi Geliştirme', 780.00],
  ['UFUK', 'Ufuk Yatırım Yönetim', 'Yatırım Yönetimi', 184.00],
  ['ULUFA', 'Ulusal Faktoring A.Ş.', 'Faktoring Çözümleri', 11.20],
  ['ULUSE', 'Ulusoy Elektrik İmalat', 'Elektrik Ekipmanları', 194.00],
  ['UNLU', 'Ünlü Yatırım Holding', 'Yatırım Bankacılığı', 16.80],
  ['VAKBN', 'Türkiye Vakıflar Bankası', 'Bankacılık Hizmetleri', 21.40],
  ['VAKFN', 'Vakıf Finansal Kiralama', 'Finansal Kiralama', 4.80],
  ['VANGD', 'Vanet Gıda Sanayi', 'Et & Şarküteri', 28.00],
  ['VERTU', 'Verusaturk Girişim Sermayesi', 'Girişim Sermayesi', 48.00],
  ['VERUS', 'Verusa Holding A.Ş.', 'Maden, Enerji & Teknoloji', 315.00],
  ['VKFYO', 'Vakıf Menkul Kıymet Yatırım', 'Menkul Kıymetler', 26.00],
  ['VKGYO', 'Vakıf Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 2.40],
  ['VKING', 'Viking Kağıt ve Selüloz', 'Kağıt & Selüloz', 36.00],
  ['YAPRK', 'Yaprak Süt ve Besi Çiftliği', 'Süt & Hayvancılık', 74.00],
  ['YAYLA', 'Yayla Enerji Üretim', 'Yenilenebilir Enerji', 18.40],
  ['YGGYO', 'Yeni Gimat Gayrimenkul', 'AVM & Gayrimenkul', 48.00],
  ['YGYO', 'Yeşil Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 8.20],
  ['YONGA', 'Yonga Mobilya Sanayi', 'Mobilya İhracatı', 68.00],
  ['YUNSA', 'Yünlü Sanayi ve Ticaret', 'Yünlü Dokuma Kumaş', 64.00],
  ['YYAPI', 'Yeşil Yapı Endüstrisi', 'İnşaat Taahhüt', 4.90],
  ['ZEDUR', 'Zedur Enerji Elektrik', 'Yenilenebilir Enerji', 14.80],
  ['ZRGYO', 'Ziraat Gayrimenkul Yatırım', 'Finans Merkezi GYO', 6.40],
  ['AVHOL', 'Avrupa Yatırım Holding', 'Sağlık & Turizm Yatırımları', 24.50],
  ['BURCE', 'Bursa Çelik Döküm Sanayi', 'Çelik Döküm İmalatı', 215.00],
  ['BURVA', 'Burçelik Vana Sanayi', 'Endüstriyel Vana İmalatı', 185.00],
  ['DAGHL', 'Dagi Yatırım Holding', 'Holding Yatırımları', 28.40],
  ['DAGI', 'Dagi Giyim Sanayi', 'İç Giyim & Mayo Perakende', 12.80],
  ['DIRIT', 'Diriteks Diriliş Tekstil', 'Battaniye & Tekstil', 14.20],
  ['DURDO', 'Duran Doğan Basım ve Ambalaj', 'Karton Ambalaj & Baskı', 16.40],
  ['EMNIS', 'Eminiş Ambalaj Sanayi', 'Plastik & Metal Kova', 142.00],
  ['GMTAS', 'Gimat Mağazacılık Sanayi', 'Gıda Perakendeciliği', 11.20],
  ['IDGYO', 'İdealist Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 5.60],
  ['KENT', 'Kent Gıda Maddeleri Sanayi', 'Şekerleme & Sakız Üretimi', 740.00],
  ['KLNMA', 'Kalkınma Bankası Yatırım', 'Yatırım Bankacılığı', 34.20],
  ['KSTUR', 'Kuştur Kuşadası Turizm', 'Otelcilik & Turizm', 5600.00],
  ['LIDFA', 'Lider Faktoring A.Ş.', 'Faktoring Hizmetleri', 11.80],
  ['MEKAG', 'Meka Beton Santralleri', 'Beton Santralleri', 64.00],
  ['MMCPS', 'MMC Sanayi ve Ticari Yatırımlar', 'Yatırım & Ticaret', 8.20],
  ['MZHLD', 'Mazhar Zorlu Holding', 'Holding Yatırımları', 7.40],
  ['ORCA', 'Orçay Ortaköy Çay Sanayi', 'Çay İmalatı & Pazarlama', 14.60],
  ['OYLUM', 'Oylum Sınai Yatırımlar', 'Bisküvi İmalatı', 9.20],
  ['RODRF', 'Rodrigo Tekstil Sanayi', 'Tekstil & Moda', 84.00],
  ['RNPOL', 'Rainbow Polikarbonat', 'Polikarbonat Levha', 28.90],
  ['SANFM', 'Sanifoam Sünger Sanayi', 'Sünger İmalatı', 28.00],
  ['SAYAS', 'Say Yenilenebilir Enerji', 'Rüzgar Türbin Parçaları', 72.00],
  ['SEKUR', 'Sekuro Plastik Sanayi', 'Plastik Ambalaj', 14.50],
  ['SELGD', 'Selçuk Gıda Sanayi', 'Kuru Meyve', 26.00],
  ['SILVR', 'Silverline Endüstri', 'Ankastre Mutfak', 18.20],
  ['SNKRN', 'Senkron Güvenlik', 'Siber Güvenlik', 38.00],
  ['SURGY', 'Sur Tatil Evleri GYO', 'Turizm Gayrimenkul', 46.00],
  ['SUNTK', 'Sun Tekstil Sanayi', 'Tekstil İhracatı', 18.60],
  ['TARKM', 'Tarkim Bitki Koruma', 'Bitki Koruma İlaçları', 580.00],
  ['TEKTU', 'Tek-Art Turizm', 'Turizm & Otelcilik', 3.80],
  ['TMPOL', 'Temapol Polimer', 'Polimer Plastik', 84.00],
  ['TNZTP', 'Tapdi Oksijen Sağlık', 'Sağlık Hizmetleri', 8.20],
  ['TUCLK', 'Tuğçelik Alüminyum', 'Alüminyum Metal', 14.20],
  ['UFUK', 'Ufuk Yatırım Yönetim', 'Yatırım Hizmetleri', 184.00],
  ['ULUFA', 'Ulusal Faktoring', 'Faktoring', 11.20],
  ['ULUSE', 'Ulusoy Elektrik', 'Elektrik Panoları', 194.00],
  ['UNLU', 'Ünlü Yatırım Holding', 'Yatırım Hizmetleri', 16.80],
  ['VANGD', 'Vanet Gıda Sanayi', 'Gıda Sanayi', 28.00],
  ['VERTU', 'Verusaturk Girişim', 'Girişim Yatırımları', 48.00],
  ['VKFYO', 'Vakıf Menkul Kıymet', 'Menkul Kıymet', 26.00],
  ['VKING', 'Viking Kağıt Selüloz', 'Kağıt Sanayi', 36.00],
  ['YAPRK', 'Yaprak Süt Besi Çiftliği', 'Süt Üretimi', 74.00],
  ['YAYLA', 'Yayla Enerji Üretim', 'Yenilenebilir Enerji', 18.40],
  ['YONGA', 'Yonga Mobilya', 'Mobilya İmalatı', 68.00],
  ['YYAPI', 'Yeşil Yapı İnşaat', 'Yapı Endüstrisi', 4.90],
  ['ZEDUR', 'Zedur Enerji', 'Elektrik Üretimi', 14.80]
];

const uniqueBistMap = new Map();
bistData.forEach(([symbol, name, sector, basePrice]) => {
  if (!uniqueBistMap.has(symbol)) {
    uniqueBistMap.set(symbol, {
      symbol,
      name,
      exchange: 'BIST',
      category: 'BIST',
      currency: '₺',
      yahooTicker: `${symbol}.IS`,
      sector,
      basePrice
    });
  }
});

const finalBist = Array.from(uniqueBistMap.values());
console.log('Final BIST count:', finalBist.length);

const bistFile = `export interface StockDefinition {
  symbol: string;
  name: string;
  exchange: string;
  category: 'BIST';
  currency: '₺';
  yahooTicker: string;
  sector: string;
  basePrice: number;
}

// BIST 300+ Hisse Senedi Takip Havuzu (Gerçek BIST Şirketleri)
export const BIST_300_STOCKS: StockDefinition[] = ${JSON.stringify(finalBist, null, 2)};
`;
fs.writeFileSync('./server/data/bistUniverse.ts', bistFile, 'utf8');

// ==========================================
// 2. GENERATE TOP 150+ CRYPTO COINS + COMMODITIES + FOREX
// ==========================================
const cryptos = [
  // Top 150+ Cryptocurrency Assets
  ['BTC', 'Bitcoin', 'Dijital Altın / Layer-1', 94250.00, 'BTC-USD'],
  ['ETH', 'Ethereum', 'Akıllı Sözleşme Platformu L1', 3420.00, 'ETH-USD'],
  ['SOL', 'Solana', 'Yüksek Hızlı Layer-1', 184.50, 'SOL-USD'],
  ['BNB', 'BNB (Binance Coin)', 'Borsa & BSC Ağı', 650.00, 'BNB-USD'],
  ['XRP', 'Ripple (XRP)', 'Sınır Ötesi Ödeme Ağı', 2.45, 'XRP-USD'],
  ['DOGE', 'Dogecoin', 'Meme & Ödeme Ağı', 0.28, 'DOGE-USD'],
  ['ADA', 'Cardano (ADA)', 'Proof-of-Stake Katman-1', 0.92, 'ADA-USD'],
  ['AVAX', 'Avalanche (AVAX)', 'Alt Ağlar & Ölçeklenebilirlik', 32.40, 'AVAX-USD'],
  ['SUI', 'Sui Network', 'Move Tabanlı Katman-1', 3.45, 'SUI20947-USD'],
  ['LINK', 'Chainlink', 'Merkeziyetsiz Veri Kahini (Oracle)', 18.20, 'LINK-USD'],
  ['NEAR', 'NEAR Protocol', 'Kullanıcı Odaklı Sharding L1', 6.20, 'NEAR-USD'],
  ['APT', 'Aptos', 'Paralel Yürütme Katman-1', 9.80, 'APT21794-USD'],
  ['DOT', 'Polkadot', 'Çok Zincirli Birlikte Çalışabilirlik', 8.50, 'DOT-USD'],
  ['LTC', 'Litecoin', 'Eşler Arası Dijital Para', 98.00, 'LTC-USD'],
  ['BCH', 'Bitcoin Cash', 'Ölçeklenebilir Ödeme Ağı', 440.00, 'BCH-USD'],
  ['UNI', 'Uniswap', 'Merkeziyetsiz Borsa (DEX)', 12.40, 'UNI7083-USD'],
  ['RENDER', 'Render Token', 'Merkeziyetsiz GPU Hesaplama', 7.40, 'RENDER-USD'],
  ['TAO', 'Bittensor (TAO)', 'Merkeziyetsiz Yapay Zeka Ağı', 480.00, 'TAO22974-USD'],
  ['FET', 'Artificial Superintelligence Alliance', 'AI Ajanları & Veri', 1.45, 'FET-USD'],
  ['ICP', 'Internet Computer', 'Merkeziyetsiz Bulut Hesaplama', 11.20, 'ICP-USD'],
  ['PEPE', 'Pepe', 'Meme Token Kültürü', 0.0000185, 'PEPE24478-USD'],
  ['SHIB', 'Shiba Inu', 'Meme & Shibarium Ekosistemi', 0.0000245, 'SHIB-USD'],
  ['XLM', 'Stellar Lumens', 'Global Ödeme Ağı', 0.48, 'XLM-USD'],
  ['TRX', 'TRON', 'Yüksek Hızlı İçerik & Stablecoin Ağı', 0.22, 'TRX-USD'],
  ['HBAR', 'Hedera Hashgraph', 'Kurumsal DLT & Hashgraph', 0.28, 'HBAR-USD'],
  ['KAS', 'Kaspa (KAS)', 'BlockDAG Tabanlı PoW L1', 0.165, 'KAS-USD'],
  ['ATOM', 'Cosmos Hub', 'Blokzincirler Arası İletişim (IBC)', 8.20, 'ATOM-USD'],
  ['ETC', 'Ethereum Classic', 'Orijinal PoW Ethereum', 28.50, 'ETC-USD'],
  ['VET', 'VeChain', 'Tedarik Zinciri & Kurumsal L1', 0.045, 'VET-USD'],
  ['FIL', 'Filecoin', 'Merkeziyetsiz Depolama Ağı', 5.60, 'FIL-USD'],
  ['IMX', 'Immutable X', 'NFT & Web3 Oyun Katman-2', 1.65, 'IMX10603-USD'],
  ['STX', 'Stacks', 'Bitcoin Akıllı Sözleşme L2', 1.85, 'STX4847-USD'],
  ['ARB', 'Arbitrum', 'Ethereum Optimistic Rollup L2', 0.85, 'ARB11841-USD'],
  ['OP', 'Optimism', 'Ethereum L2 & Süperzincir', 1.95, 'OP-USD'],
  ['TIA', 'Celestia', 'Modüler Veri Erişilebilirlik Ağı', 5.80, 'TIA22861-USD'],
  ['INJ', 'Injective Protocol', 'Finans İçin Optimize Katman-1', 24.50, 'INJ-USD'],
  ['FTM', 'Fantom (Sonic)', 'Yüksek Verimli Directed Acyclic Graph', 0.88, 'FTM-USD'],
  ['ALGO', 'Algorand', 'Pure Proof-of-Stake L1', 0.38, 'ALGO-USD'],
  ['THETA', 'Theta Network', 'Merkeziyetsiz Video Akış Ağı', 1.85, 'THETA-USD'],
  ['GRT', 'The Graph', 'Blokzincir Veri İndeksleme Protokolü', 0.26, 'GRT6719-USD'],
  ['SEI', 'Sei Network', 'DEX Odaklı Hızlı Katman-1', 0.54, 'SEI-USD'],
  ['JUP', 'Jupiter (JUP)', 'Solana Likidite ve DEX Toplayıcı', 1.15, 'JUP29210-USD'],
  ['PYTH', 'Pyth Network', 'Düşük Gecikmeli Finansal Oracle', 0.42, 'PYTH-USD'],
  ['WIF', 'dogwifhat', 'Solana Meme Token', 2.85, 'WIF-USD'],
  ['BONK', 'Bonk (BONK)', 'Solana Topluluk Meme Coini', 0.000032, 'BONK-USD'],
  ['FLOKI', 'Floki', 'Meme & Web3 Oyun Ekosistemi', 0.00021, 'FLOKI-USD'],
  ['POL', 'Polygon (POL/MATIC)', 'Ethereum Yan Zincir & ZK-Rollup', 0.52, 'MATIC-USD'],
  ['AAVE', 'Aave', 'Merkeziyetsiz Borç Alma/Verme', 195.00, 'AAVE-USD'],
  ['MKR', 'Maker (Sky)', 'Dai Stablecoin Yönetişim', 1850.00, 'MKR-USD'],
  ['LDO', 'Lido DAO', 'Ethereum Likit Staking Protokolü', 1.65, 'LDO-USD'],
  ['QNT', 'Quant Network', 'Kurumsal Blokzincir Birlikte Çalışabilirlik', 115.00, 'QNT-USD'],
  ['CRV', 'Curve DAO Token', 'Stablecoin DEX & Likidite', 0.65, 'CRV-USD'],
  ['ENA', 'Ethena (ENA)', 'Sentetik Dolar & Getiri Protokolü', 0.82, 'ENA-USD'],
  ['ONDO', 'Ondo Finance', 'Gerçek Dünya Varlıkları (RWA)', 1.28, 'ONDO-USD'],
  ['STRK', 'Starknet', 'ZK-STARK Tabanlı Ethereum L2', 0.55, 'STRK22691-USD'],
  ['WLD', 'Worldcoin', 'Biyometrik Kimlik Doğrulama & AI', 2.65, 'WLD-USD'],
  ['GALA', 'Gala Games', 'Web3 Oyun ve Eğlence Ekosistemi', 0.038, 'GALA-USD'],
  ['SAND', 'The Sandbox', 'Metaverse Sanal Dünya & NFT', 0.48, 'SAND-USD'],
  ['MANA', 'Decentraland', 'Sanal Gerçeklik & Metaverse L1', 0.45, 'MANA-USD'],
  ['CHZ', 'Chiliz', 'Spor Fan Token Ekosistemi L1', 0.082, 'CHZ-USD'],
  ['AXS', 'Axie Infinity', 'NFT Tabanlı Oyna-Kazan Oyunu', 7.40, 'AXS-USD'],
  ['RUNE', 'THORChain', 'Çapraz Zincir Likidite Protokolü', 5.80, 'RUNE-USD'],
  ['BEAM', 'Beam (Merit Circle)', 'Web3 Oyun Altyapı Ağı', 0.024, 'BEAM28298-USD'],
  ['BLUR', 'Blur', 'Profesyonel NFT Pazaryeri', 0.32, 'BLUR-USD'],
  ['ENS', 'Ethereum Name Service', 'Web3 Alan Adı ve Kimlik', 28.50, 'ENS-USD'],
  ['DYDX', 'dYdX', 'Türev İşlemler & Sürekli Vadeli DEX', 1.45, 'DYDX-USD'],
  ['PENDLE', 'Pendle Finance', 'Gelecek Getiri Alım Satım Protokolü', 4.80, 'PENDLE-USD'],
  ['1INCH', '1inch Network', 'DEX Likidite Toplayıcı', 0.42, '1INCH-USD'],
  ['COMP', 'Compound', 'Otomatik Faiz Getirisi Protokolü', 62.00, 'COMP5692-USD'],
  ['SNX', 'Synthetix Network', 'Sentetik Varlıklar & Türevler', 1.85, 'SNX-USD'],
  ['CAKE', 'PancakeSwap', 'BSC Lider DEX ve Launchpad', 2.45, 'CAKE-USD'],
  ['SUSHI', 'SushiSwap', 'Çok Zincirli Otomatik Piyasa Yapıcı', 1.10, 'SUSHI-USD'],
  ['ZEC', 'Zcash', 'Sıfır Bilgi İspatlı Gizlilik Parası', 48.00, 'ZEC-USD'],
  ['DASH', 'Dash', 'Hızlı ve Gizli Ödeme Parası', 34.00, 'DASH-USD'],
  ['XMR', 'Monero', 'Tamamen İzlenemez Gizlilik Parası', 165.00, 'XMR-USD'],
  ['EOS', 'EOS Network', 'Düşük Gecikmeli DApp Katman-1', 0.78, 'EOS-USD'],
  ['NEO', 'NEO', 'Akıllı Ekonomi & Sözleşmeler L1', 14.50, 'NEO-USD'],
  ['IOTA', 'IOTA (MIOTA)', 'Nesnelerin İnterneti (IoT) Tangle', 0.28, 'IOTA-USD'],
  ['KAVA', 'Kava', 'Cosmos ve Ethereum Hibrit L1', 0.54, 'KAVA-USD'],
  ['ROSE', 'Oasis Network', 'Gizlilik Odaklı Katman-1', 0.088, 'ROSE-USD'],
  ['AKT', 'Akash Network', 'Merkeziyetsiz Bulut GPU Pazarı', 3.80, 'AKT-USD'],
  ['GNO', 'Gnosis', 'Merkeziyetsiz Tahmin & Altyapı', 285.00, 'GNO-USD'],
  ['SUPER', 'SuperVerse', 'Web3 Oyun ve NFT Ekosistemi', 1.35, 'SUPER-USD'],
  ['WAXP', 'WAX Protocol', 'NFT ve Dijital Koleksiyon Ağı', 0.048, 'WAXP-USD'],
  ['HOT', 'Holo (HOT)', 'Eşler Arası Dağıtık Ağ', 0.0022, 'HOT-USD'],
  ['ZIL', 'Zilliqa', 'Sharding Tabanlı Katman-1', 0.024, 'ZIL-USD'],
  ['ENJ', 'Enjin Coin', 'Web3 Oyun Varlıkları Protokolü', 0.22, 'ENJ-USD'],
  ['BAT', 'Basic Attention Token', 'Brave Tarayıcı Dijital Reklam', 0.24, 'BAT-USD'],
  ['MINA', 'Mina Protocol', 'Dünyanın En Hafif ZK Blokzinciri', 0.68, 'MINA-USD'],
  ['FLOW', 'Flow', 'Yeni Nesil Oyun & Tüketici L1', 0.72, 'FLOW-USD'],
  ['CELO', 'Celo', 'Mobil Odaklı Ödeme Katman-2', 0.78, 'CELO-USD'],
  ['CFX', 'Conflux Network', 'Tree-Graph Konsensüs Katman-1', 0.18, 'CFX-USD'],
  ['JASMY', 'JasmyCoin', 'IoT & Kişisel Veri Güvenliği', 0.026, 'JASMY-USD'],
  ['QTUM', 'Qtum', 'UTXO ve EVM Hibrit Katman-1', 3.60, 'QTUM-USD'],
  ['ONT', 'Ontology', 'Merkeziyetsiz Kimlik ve Veri Ağı', 0.28, 'ONT-USD'],
  ['RVN', 'Ravencoin', 'Varlık Transferi PoW Blokzinciri', 0.022, 'RVN-USD'],
  ['SC', 'Siacoin', 'Merkeziyetsiz Bulut Depolama', 0.0058, 'SC-USD'],
  ['RAY', 'Raydium', 'Solana Otomatik Piyasa Yapıcı (AMM)', 4.60, 'RAY-USD'],
  ['ORDI', 'Ordinals (ORDI)', 'Bitcoin BRC-20 Protokolü', 38.00, 'ORDI-USD'],
  ['SATS', '1000SATS', 'Bitcoin Satoshileri BRC-20', 0.00028, 'SATS-USD'],
  ['BOME', 'BOOK OF MEME', 'Solana Meme & Depolama', 0.0094, 'BOME-USD'],
  ['MEW', 'cat in a dogs world', 'Solana Kedi Meme Tokeni', 0.0078, 'MEW-USD'],
  ['NOT', 'Notcoin', 'Telegram Tap-to-Earn Oyunu', 0.0084, 'NOT-USD'],
  ['TON', 'Toncoin', 'Telegram Entegre Katman-1 Ağı', 5.80, 'TON11419-USD'],
  ['AEVO', 'Aevo', 'Yüksek Performanslı L2 Opsiyon DEX', 0.46, 'AEVO-USD'],
  ['ETHFI', 'ether.fi', 'Merkeziyetsiz Likit Yeniden Staking', 1.85, 'ETHFI-USD'],
  ['EIGEN', 'EigenLayer', 'Ethereum Yeniden Staking (Restaking)', 3.40, 'EIGEN-USD'],
  ['IO', 'io.net', 'Merkeziyetsiz AI Hesaplama & GPU', 2.45, 'IO-USD'],
  ['SAFE', 'Safe (Gnosis Safe)', 'Çoklu İmzalı Akıllı Cüzdan Altyapısı', 1.15, 'SAFE-USD'],
  ['BB', 'BounceBit', 'BTC Yeniden Staking Katman-1', 0.38, 'BB-USD'],
  ['LISTA', 'Lista DAO', 'Likit Staking & Stablecoin Borçlanma', 0.44, 'LISTA-USD'],
  ['ZRO', 'LayerZero', 'Her Şeyi Birbirine Bağlayan Zincirlerarası İletişim', 4.80, 'ZRO-USD'],
  ['DRIFT', 'Drift Protocol', 'Solana Tabanlı Sürekli Vadeli DEX', 1.45, 'DRIFT-USD'],
  ['TNSR', 'Tensor', 'Solana Lider NFT Pazaryeri', 0.62, 'TNSR-USD'],
  ['OMNI', 'Omni Network', 'Ethereum Rollup Birlikte Çalışabilirlik', 8.50, 'OMNI-USD'],
  ['REZ', 'Renzo', 'Cross-chain Likit Yeniden Staking', 0.048, 'REZ-USD'],
  ['SAGA', 'Saga', 'Özel Uygulama Blokzincirleri (Chainlets)', 1.95, 'SAGA-USD'],
  ['W', 'Wormhole', 'Çok Zincirli Birlikte Çalışabilirlik Köprüsü', 0.28, 'W-USD'],
  ['PIXEL', 'Pixels', 'Web3 Sosyal Çiftçilik Oyunu', 0.18, 'PIXEL-USD'],
  ['ALT', 'AltLayer', 'Rollup Hizmeti ve Yeniden Staking', 0.12, 'ALT-USD'],
  ['MANTA', 'Manta Network', 'Modüler ZK-Rollup Katman-2', 0.85, 'MANTA-USD'],
  ['AI', 'Sleepless AI', 'Yapay Zeka & Sanal Arkadaşlık Oyunu', 0.52, 'AI-USD'],
  ['XAI', 'Xai', 'Arbitrum Tabanlı Web3 Oyun Katman-3', 0.26, 'XAI-USD'],
  ['NFP', 'NFPrompt', 'AI Destekli Web3 İçerik Platformu', 0.24, 'NFP-USD'],
  ['ACE', 'Fusionist (ACE)', 'Yüksek Kaliteli Web3 Bilimkurgu Oyunu', 2.40, 'ACE-USD'],
  ['JTO', 'Jito', 'Solana MEV & Likit Staking Protokolü', 3.10, 'JTO-USD'],
  ['AUCTION', 'Bounce Token', 'Merkeziyetsiz Müzayede Protokolü', 16.50, 'AUCTION-USD'],
  ['TRB', 'Tellor', 'Merkeziyetsiz Oracle Katmanı', 68.00, 'TRB-USD'],
  ['BIGTIME', 'Big Time', 'Oynaması Ücretsiz Web3 MMORPG', 0.16, 'BIGTIME-USD'],
  ['LOOM', 'Loom Network', 'Yüksek Performanslı DApp Zinciri', 0.068, 'LOOM-USD'],
  ['BLZ', 'Bluzelle', 'Web3 Oyun ve Merkeziyetsiz Depolama', 0.14, 'BLZ-USD'],
  ['CYBER', 'CyberConnect', 'Web3 Sosyal Grafik Protokolü', 3.80, 'CYBER-USD'],
  ['ARK', 'Ark', 'Kullanımı Kolay Blokzincir Ekosistemi', 0.58, 'ARK-USD'],
  ['MAV', 'Maverick Protocol', 'Dinamik Dağıtım AMM Protokolü', 0.22, 'MAV-USD'],
  ['RAD', 'Radicle', 'Merkeziyetsiz Kod İşbirliği & Git', 1.45, 'RAD-USD'],
  ['ID', 'SPACE ID', 'Evrensel Web3 Alan Adı Hizmeti', 0.44, 'ID-USD'],
  ['RDNT', 'Radiant Capital', 'Çok Zincirli Para Piyasası Protokolü', 0.068, 'RDNT-USD'],
  ['GNS', 'Gains Network', 'Merkeziyetsiz Kaldıraçlı Alım Satım', 2.10, 'GNS-USD'],
  ['SSV', 'SSV Network', 'Merkeziyetsiz Ethereum Doğrulayıcı Ağı', 24.00, 'SSV-USD'],
  ['LQTY', 'Liquity', 'Faizsiz Borçlanma Protokolü', 1.15, 'LQTY-USD'],
  ['ACH', 'Alchemy Pay', 'Kripto-Fiat Hibrit Ödeme Ağ Geçidi', 0.024, 'ACH-USD'],
  ['HOOK', 'Hooked Protocol', 'Web3 Öğrenme ve Katılım Platformu', 0.48, 'HOOK-USD'],
  ['MAGIC', 'Treasure (MAGIC)', 'Arbitrum Web3 Oyun Ekosistemi', 0.42, 'MAGIC-USD'],
  ['HFT', 'Hashflow', 'Sıfır Slippage DEX Protokolü', 0.18, 'HFT-USD'],
  ['OSMO', 'Osmosis', 'Cosmos IBC Lider DEX ve Likidite', 0.58, 'OSMO-USD'],
  ['GMX', 'GMX', 'Merkeziyetsiz Sürekli Vadeli Alım Satım', 28.00, 'GMX-USD'],
  ['STG', 'Stargate Finance', 'Çapraz Zincir Likidite Taşıyıcı', 0.34, 'STG-USD'],
  ['AERO', 'Aerodrome Finance', 'Base Ağı Merkezi Likidite Motoru', 1.35, 'AERO-USD'],
  ['VIRTUAL', 'Virtuals Protocol', 'Yapay Zeka ve Oyun Ajanları Protokolü', 1.85, 'VIRTUAL-USD'],
  ['AI16Z', 'ai16z', 'Merkeziyetsiz AI Fon ve Ajan DAO', 0.48, 'AI16Z-USD'],
  ['FARTCOIN', 'Fartcoin', 'Viral AI & Meme Token', 0.65, 'FARTCOIN-USD'],
  ['GOAT', 'Goatseus Maximus', 'AI Ajanı Tabanlı Meme Token', 0.78, 'GOAT-USD'],
  ['GRASS', 'Grass', 'Merkeziyetsiz Web Kazıma ve AI Veri Ağı', 2.65, 'GRASS-USD'],
  ['PNUT', 'Peanut the Squirrel', 'Topluluk Meme Tokeni', 0.88, 'PNUT-USD'],
  ['ACT', 'Act I: The AI Prophecy', 'Açık Kaynak AI ve Ajan Ekosistemi', 0.42, 'ACT-USD'],
  ['CHILLGUY', 'Just a Chill Guy', 'Viral Karakter Meme Tokeni', 0.38, 'CHILLGUY-USD'],
  ['MOODENG', 'Moo Deng', 'Viral Su Aygırı Meme Tokeni', 0.32, 'MOODENG-USD']
];

const commoditiesAndForex = [
  // Değerli Madenler & Emtialar
  { symbol: 'XAU/USD', name: 'Ons Altın (USD)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'GC=F', sector: 'Kıymetli Maden', basePrice: 4650.78 },
  { symbol: 'ALTIN', name: 'Gram Altın (TL)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '₺', sector: 'Fiziki Altın', basePrice: 5472.50 },
  { symbol: 'CEYREK', name: 'Çeyrek Altın (TL)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '₺', sector: 'Sarrafiye', basePrice: 8947.50 },
  { symbol: 'YARIM', name: 'Yarım Altın (TL)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '₺', sector: 'Sarrafiye', basePrice: 17895.00 },
  { symbol: 'TAM', name: 'Tam / Cumhuriyet Altını (TL)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '₺', sector: 'Sarrafiye', basePrice: 35790.00 },
  { symbol: 'ATA', name: 'Ata Altın (TL)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '₺', sector: 'Sarrafiye', basePrice: 36700.00 },
  { symbol: 'XAG/USD', name: 'Ons Gümüş (USD)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'SI=F', sector: 'Kıymetli Maden', basePrice: 31.85 },
  { symbol: 'GUMUS', name: 'Gram Gümüş (TL)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '₺', sector: 'Fiziki Gümüş', basePrice: 37.50 },
  { symbol: 'BRENT', name: 'Brent Ham Petrol', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'BZ=F', sector: 'Enerji Emtiası', basePrice: 74.80 },
  { symbol: 'CRUDE_OIL', name: 'WTI Ham Petrol (USD)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'CL=F', sector: 'Enerji Emtiası', basePrice: 71.20 },
  { symbol: 'NATGAS', name: 'Doğal Gaz (USD)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'NG=F', sector: 'Enerji Emtiası', basePrice: 3.25 },
  { symbol: 'COPPER', name: 'Bakır (USD)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'HG=F', sector: 'Sanayi Metali', basePrice: 4.15 },
  { symbol: 'PLATINUM', name: 'Platin (USD)', exchange: 'COMMODITIES', category: 'COMMODITIES', currency: '$', yahooTicker: 'PL=F', sector: 'Kıymetli Maden', basePrice: 965.00 },

  // Döviz & Forex Pariteleri
  { symbol: 'USD/TRY', name: 'Dolar / Türk Lirası', exchange: 'FOREX', category: 'FOREX', currency: '₺', yahooTicker: 'TRY=X', sector: 'Döviz Kuru', basePrice: 36.45 },
  { symbol: 'EUR/TRY', name: 'Euro / Türk Lirası', exchange: 'FOREX', category: 'FOREX', currency: '₺', yahooTicker: 'EURTRY=X', sector: 'Döviz Kuru', basePrice: 38.10 },
  { symbol: 'GBP/TRY', name: 'İngiliz Sterlini / Türk Lirası', exchange: 'FOREX', category: 'FOREX', currency: '₺', yahooTicker: 'GBPTRY=X', sector: 'Döviz Kuru', basePrice: 46.20 },
  { symbol: 'EUR/USD', name: 'Euro / Amerikan Doları', exchange: 'FOREX', category: 'FOREX', currency: '$', yahooTicker: 'EURUSD=X', sector: 'Majör Parite', basePrice: 1.045 },
  { symbol: 'GBP/USD', name: 'Sterlin / Amerikan Doları', exchange: 'FOREX', category: 'FOREX', currency: '$', yahooTicker: 'GBPUSD=X', sector: 'Majör Parite', basePrice: 1.265 },
  { symbol: 'USD/JPY', name: 'Amerikan Doları / Japon Yeni', exchange: 'FOREX', category: 'FOREX', currency: '¥', yahooTicker: 'USDJPY=X', sector: 'Majör Parite', basePrice: 154.20 },
  { symbol: 'DXY', name: 'ABD Dolar Endeksi', exchange: 'FOREX', category: 'FOREX', currency: '$', yahooTicker: 'DX-Y.NYB', sector: 'Makro Dolar Endeksi', basePrice: 106.80 }
];

const cryptoAssetList = cryptos.map(([symbol, name, sector, basePrice, yahooTicker]) => ({
  symbol,
  name,
  exchange: 'CRYPTO',
  category: 'CRYPTO',
  currency: '$',
  yahooTicker,
  sector,
  basePrice
}));

console.log('Top Crypto count:', cryptoAssetList.length);

const allMacroAndCrypto = [
  ...commoditiesAndForex,
  ...cryptoAssetList
];

const cryptoFile = `export interface MacroAssetDefinition {
  symbol: string;
  name: string;
  exchange: string;
  category: 'CRYPTO' | 'COMMODITIES' | 'FOREX';
  currency: string;
  yahooTicker?: string;
  sector: string;
  basePrice: number;
}

// 150+ Lider Kripto Varlık + Emtialar + Döviz Kurları
export const MACRO_AND_CRYPTO_ASSETS: MacroAssetDefinition[] = ${JSON.stringify(allMacroAndCrypto, null, 2)};
`;
fs.writeFileSync('./server/data/cryptoAndCommodities.ts', cryptoFile, 'utf8');

console.log('Successfully wrote cryptoAndCommodities.ts with', cryptoAssetList.length, 'crypto assets + commodities/forex.');
