const fs = require('fs');

// 1. GENERATE BIST 300+ UNIVERSE
const bistListRaw = [
  // BIST 30 & Large Cap
  ['THYAO', 'Türk Hava Yolları', 'Havacılık', 308.50],
  ['ASELS', 'Aselsan Savunma Sanayi', 'Savunma Sanayi', 72.80],
  ['TUPRS', 'Tüpraş Petrol Rafinerileri', 'Enerji & Petrol', 154.60],
  ['KCHOL', 'Koç Holding', 'Holding', 202.40],
  ['EREGL', 'Ereğli Demir Çelik', 'Demir Çelik', 49.60],
  ['BIMAS', 'BİM Birleşik Mağazalar', 'Perakende', 486.00],
  ['SISE', 'Şişecam Cam Sanayii', 'Cam & Sanayi', 47.30],
  ['AKBNK', 'Akbank T.A.Ş.', 'Bankacılık', 58.90],
  ['GARAN', 'Garanti BBVA', 'Bankacılık', 114.80],
  ['YKBNK', 'Yapı ve Kredi Bankası', 'Bankacılık', 32.90],
  ['ISCTR', 'Türkiye İş Bankası (C)', 'Bankacılık', 14.75],
  ['SAHOL', 'Sabancı Holding', 'Holding', 94.50],
  ['FROTO', 'Ford Otomotiv Sanayi', 'Otomotiv', 1130.00],
  ['PGSUS', 'Pegasus Hava Taşımacılığı', 'Havacılık', 239.00],
  ['TOASO', 'Tofaş Türk Otomobil Fabrikası', 'Otomotiv', 245.00],
  ['TCELL', 'Turkcell İletişim Hizmetleri', 'Telekomünikasyon', 98.40],
  ['TTKOM', 'Türk Telekomünikasyon', 'Telekomünikasyon', 52.60],
  ['ENKAI', 'Enka İnşaat ve Sanayi', 'İnşaat & Taahhüt', 46.80],
  ['EKGYO', 'Emlak Konut Gayrimenkul Yatırım', 'Gayrimenkul', 11.85],
  ['PETKM', 'Petkim Petrokimya Holding', 'Kimya & Petrokimya', 21.40],
  ['ASTOR', 'Astor Enerji A.Ş.', 'Enerji & Ekipman', 96.20],
  ['KONTG', 'Kontrolmatik Teknoloji Enerji', 'Teknoloji & Enerji', 58.40],
  ['SASA', 'SASA Polyester Sanayi', 'Kimya & Tekstil', 4.85],
  ['HEKTS', 'Hektaş Ticaret T.A.Ş.', 'Tarım & Kimya', 3.95],
  ['CCOLA', 'Coca-Cola İçecek A.Ş.', 'Gıda & İçecek', 68.50],
  ['MGROS', 'Migros Ticaret A.Ş.', 'Perakende', 512.00],
  ['KOZAL', 'Koza Altın İşletmeleri', 'Madencilik', 23.40],
  ['KOZAA', 'Koza Anadolu Metal Madencilik', 'Madencilik', 62.50],
  ['IPEKE', 'İpek Doğal Enerji Kaynakları', 'Madencilik & Enerji', 44.80],
  ['ALARK', 'Alarko Holding', 'Holding & Enerji', 104.20],
  ['ARCLK', 'Arçelik A.Ş.', 'Dayanıklı Tüketim', 162.00],
  ['VESTL', 'Vestel Elektronik Sanayi', 'Elektronik & Tüketim', 78.40],
  ['VESBE', 'Vestel Beyaz Eşya Sanayi', 'Dayanıklı Tüketim', 21.60],
  ['OYAKC', 'OYAK Çimento Fabrikaları', 'Çimento & Yapı', 68.30],
  ['CIMSA', 'Çimsa Çimento Sanayi', 'Çimento & Yapı', 35.80],
  ['AKCNS', 'Akçansa Çimento Sanayi', 'Çimento & Yapı', 158.00],
  ['SOKM', 'Şok Marketler Ticaret', 'Perakende', 51.50],
  ['BIZIM', 'Bizim Toptan Satış Mağazaları', 'Perakende', 39.20],
  ['TAVHL', 'TAV Havalimanları Holding', 'Havacılık & Liman', 242.00],
  ['CLEBI', 'Çelebi Hava Servisi', 'Havacılık Hizmetleri', 1840.00],
  ['GUBRF', 'Gübre Fabrikaları T.A.Ş.', 'Tarım & Gübre', 178.00],
  ['BAGFS', 'Bağfaş Bandırma Gübre Fabrikaları', 'Tarım & Gübre', 28.50],
  ['EGEEN', 'Ege Endüstri ve Ticaret', 'Otomotiv Yan Sanayi', 12450.00],
  ['BRISA', 'Brisa Bridgestone Lastik Sanayi', 'Otomotiv & Lastik', 118.00],
  ['GOODY', 'Goodyear Lastikleri T.A.Ş.', 'Otomotiv & Lastik', 22.40],
  ['OTKAR', 'Otokar Otomotiv ve Savunma', 'Otomotiv & Savunma', 525.00],
  ['DOAS', 'Doğuş Otomotiv Servis', 'Otomotiv & Dağıtım', 284.00],
  ['TMSN', 'Tümosan Motor ve Traktör', 'Otomotiv & Makine', 126.00],
  ['KARSN', 'Karsan Otomotiv Sanayii', 'Otomotiv & Ulaşım', 12.80],
  ['ASUZU', 'Anadolu Isuzu Otomotiv', 'Otomotiv & Ticari Araç', 212.00],
  ['KRDMD', 'Kardemir Karabük Demir Çelik (D)', 'Demir Çelik', 27.80],
  ['KRDMA', 'Kardemir Karabük Demir Çelik (A)', 'Demir Çelik', 25.40],
  ['KRDMB', 'Kardemir Karabük Demir Çelik (B)', 'Demir Çelik', 24.60],
  ['CEMTS', 'Çemtaş Çelik Makina Sanayi', 'Demir Çelik & Makine', 11.90],
  ['BUCIM', 'Bursa Çimento Fabrikası', 'Çimento & Yapı', 8.45],
  ['NUHCM', 'Nuh Çimento Sanayi', 'Çimento & Yapı', 315.00],
  ['AFYON', 'Afyon Çimento Sanayi', 'Çimento & Yapı', 13.80],
  ['BTCIM', 'Batıçim Batı Anadolu Çimento', 'Çimento & Yapı', 142.00],
  ['CANTE', 'Çan2 Termik A.Ş.', 'Enerji & Üretim', 16.50],
  ['ODAS', 'Odaş Elektrik Üretim', 'Enerji & Madencilik', 7.95],
  ['AKSEN', 'Aksa Enerji Üretim', 'Enerji & Üretim', 41.60],
  ['ZOREN', 'Zorlu Enerji Elektrik Üretim', 'Enerji & Yenilenebilir', 4.85],
  ['GWIND', 'Galata Wind Enerji A.Ş.', 'Yenilenebilir Enerji', 28.90],
  ['ENJSA', 'Enerjisa Enerji A.Ş.', 'Enerji Dağıtım', 63.40],
  ['AKENR', 'Akenerji Elektrik Üretim', 'Enerji & Üretim', 17.20],
  ['CWENE', 'CW Enerji Mühendislik', 'Güneş Enerjisi & Teknoloji', 210.00],
  ['EUPWR', 'Europower Enerji ve Otomasyon', 'Elektrik & Otomasyon', 92.50],
  ['ALFAS', 'Alfa Solar Enerji Sanayi', 'Güneş Enerjisi', 74.80],
  ['KOPOL', 'Koza Polyester Sanayi', 'Kimya & Tekstil', 42.50],
  ['SDTTR', 'SDT Uzay ve Savunma Teknolojileri', 'Savunma & Uzay', 285.00],
  ['MIATK', 'Mia Teknoloji A.Ş.', 'Yazılım & Bilişim', 58.20],
  ['REEDR', 'Reeder Teknoloji Sanayi', 'Elektronik & Teknoloji', 23.90],
  ['VBTYZ', 'VBT Yazılım A.Ş.', 'Yazılım & Bilişim', 38.60],
  ['ARDYZ', 'Ard Grup Bilişim Teknolojileri', 'Bilişim Teknolojileri', 46.20],
  ['PAPIL', 'Papilon Savunma Güvenlik', 'Biyometri & Savunma', 94.00],
  ['AGESA', 'Agesa Hayat ve Emeklilik', 'Sigortacılık', 118.00],
  ['ANSGR', 'Anadolu Anonim Türk Sigorta', 'Sigortacılık', 96.50],
  ['AKGRT', 'Aksigorta A.Ş.', 'Sigortacılık', 8.20],
  ['TURSG', 'Türkiye Sigorta A.Ş.', 'Sigortacılık', 64.00],
  ['ANHYT', 'Anadolu Hayat Emeklilik', 'Sigortacılık & Bireysel Emeklilik', 98.00],
  ['ISGYO', 'İş Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 16.40],
  ['TRGYO', 'Torunlar Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 48.60],
  ['OZKGY', 'Özak Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 10.20],
  ['DGGYO', 'Doğuş Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 52.00],
  ['SNGYO', 'Sinpaş Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 4.60],
  ['KLGYO', 'Kiler Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 4.90],
  ['HLGYO', 'Halk Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Yatırım', 5.40],
  ['VAKKO', 'Vakko Tekstil ve Hazır Giyim', 'Tekstil & Lüks Giyim', 94.00],
  ['MAVI', 'Mavi Giyim Sanayi ve Ticaret', 'Tekstil & Moda', 92.50],
  ['YATAS', 'Yataş Yatak ve Yorgan Sanayi', 'Mobilya & Ev Tekstili', 34.80],
  ['DESA', 'Desa Deri Sanayi ve Ticaret', 'Deri & Moda', 21.40],
  ['DERIM', 'Derimod Konfeksiyon Ayakkabı', 'Deri & Ayakkabı', 36.80],
  ['BRKO', 'Birko Birleşik Koyunlular Mensucat', 'Tekstil & Mensucat', 7.40],
  ['SKBNK', 'Şekerbank T.A.Ş.', 'Bankacılık', 4.95],
  ['TSKB', 'Türkiye Sınai Kalkınma Bankası', 'Kalkınma Bankacılığı', 12.80],
  ['ALBRK', 'Albaraka Türk Katılım Bankası', 'Katılım Bankacılığı', 5.85],
  ['SELEC', 'Selçuk Ecza Deposu Ticaret', 'Sağlık & İlaç Dağıtım', 64.50],
  ['LOGO', 'Logo Yazılım Sanayi ve Ticaret', 'Kurumsal Yazılım', 96.00],
  ['NETAS', 'Netaş Telekomünikasyon', 'Telekom Altyapı & Bilişim', 72.00],
  ['INDES', 'İndeks Bilgisayar Sistemleri', 'Bilişim & Dağıtım', 8.90],
  ['ARENA', 'Arena Bilgisayar Sanayi', 'Bilişim Dağıtım', 42.00],
  ['DGATE', 'Datagate Bilgisayar Malzemeleri', 'Bilişim Ekipmanları', 39.50],
  ['PKART', 'Plastikkart Akıllı Kart İletişim', 'Akıllı Kart & Güvenlik', 124.00],
  ['LINK', 'Link Bilgisayar Sistemleri', 'Yazılım & ERP', 485.00],
  ['DESPC', 'Despec Bilgisayar Pazarlama', 'Bilişim Sarf Malzemeleri', 41.50],
  ['FONET', 'Fonet Bilgi Teknolojileri', 'Sağlık Bilişimi', 26.80],
  ['SMART', 'Smartiks Yazılım A.Ş.', 'Yazılım & Veri', 64.00],
  ['MOBTL', 'Mobiltel İletişim Hizmetleri', 'Telekom Dağıtım', 4.40],
  ['KRONT', 'Kron Telekomünikasyon', 'Siber Güvenlik & Telekom', 26.50],
  ['FORTE', 'Forte Bilgi İletişim Teknolojileri', 'Bilişim & Savunma Yazılım', 68.00],
  ['TABGD', 'TAB Gıda Sanayi ve Ticaret', 'Hızlı Servis Restoran', 148.00],
  ['OBAMS', 'Oba Makarnacılık Sanayi', 'Gıda & Makarna', 37.80],
  ['TATGD', 'Tat Gıda Sanayi A.Ş.', 'Gıda & Konserve', 26.40],
  ['ULUUN', 'Ulusoy Un Sanayi ve Ticaret', 'Gıda & Un Sanayi', 28.50],
  ['TUKAS', 'Tukaş Gıda Sanayi ve Ticaret', 'Gıda Sanayi', 7.45],
  ['BANVT', 'Banvit Bandırma Vitaminli Yem', 'Gıda & Kanatlı Hayvancılık', 380.00],
  ['DARDL', 'Dardanel Önentaş Gıda Sanayi', 'Gıda & Su Ürünleri', 5.60],
  ['SELVA', 'Selva Gıda Sanayi A.Ş.', 'Gıda Ürünleri', 14.80],
  ['PETUN', 'Pınar Entegre Et ve Un Sanayi', 'Gıda & Et Ürünleri', 94.00],
  ['PNSUT', 'Pınar Süt Mamülleri Sanayii', 'Gıda & Süt Ürünleri', 86.50],
  ['PINSU', 'Pınar Su ve İçecek Sanayi', 'Gıda & İçecek', 22.80],
  ['AEFES', 'Anadolu Efes Biracılık ve Malt', 'İçecek & Malt Sanayi', 198.00],
  ['TBORG', 'Türk Tuborg Bira ve Malt Sanayi', 'İçecek Sanayi', 112.00],
  ['YYLGD', 'Yayla Agro Gıda Sanayi', 'Gıda & Bakliyat', 13.60],
  ['GOKNR', 'Göknur Gıda Maddeleri Enerji', 'Meyve Suyu & Konsantre', 28.40],
  ['KAYSE', 'Kayseri Şeker Fabrikası', 'Gıda & Şeker Sanayi', 29.50],
  ['MEKAG', 'Meka Beton Santralleri İmalat', 'Makine & İmalat', 64.00],
  ['ENERY', 'Enerya Enerji A.Ş.', 'Doğalgaz Dağıtım', 184.00],
  ['AHGAZ', 'Ahlatcı Doğal Gaz Dağıtım', 'Doğalgaz Dağıtım & Finans', 14.20],
  ['MANAS', 'Manas Enerji Yönetimi Sanayi', 'Enerji Yönetim Sistemleri', 11.20],
  ['SAYAS', 'Say Yenilenebilir Enerji Ekipmanları', 'Rüzgar & Güneş Ekipman', 72.00],
  ['YEOTK', 'YEO Teknoloji Enerji ve Endüstri', 'Enerji & Otomasyon Mühendislik', 196.00],
  ['BIOEN', 'Biotrend Çevre ve Enerji Yatırımları', 'Biyokütle & Çevre Enerji', 18.90],
  ['CONSE', 'Consus Enerji İşletmeciliği', 'Biyokütle & Güneş Enerji', 6.80],
  ['HUNER', 'Hun Yenilenebilir Enerji', 'Yenilenebilir Enerji', 4.90],
  ['MAGEN', 'Margün Trend Enerji Yatırım', 'Güneş Enerjisi Santralleri', 12.80],
  ['ESEN', 'Esenboğa Elektrik Üretim', 'Güneş Enerjisi', 22.40],
  ['NATEN', 'Naturel Yenilenebilir Enerji', 'Güneş Enerjisi Yatırımları', 54.00],
  ['PAMEL', 'Pamel Yenilenebilir Elektrik Üretim', 'Hidroelektrik Santralleri', 142.00],
  ['AYDEM', 'Aydem Yenilenebilir Enerji', 'Yenilenebilir Enerji', 24.60],
  ['KAREL', 'Karel Elektronik Sanayi', 'Elektronik & İletişim Sistemleri', 14.80],
  ['ESCOM', 'Escort Teknoloji Yatırım', 'Bilişim & Girişim Yatırım', 44.00],
  ['KFEIN', 'Kafein Yazılım Hizmetleri', 'Yazılım Geliştirme', 114.00],
  ['TMPOL', 'Temapol Polimer Plastik', 'Plastik & Polimer Levha', 84.00],
  ['BRMEN', 'Birlik Mensucat Ticaret', 'Tekstil & Sanayi', 7.10],
  ['BRKSN', 'Berkosan Yalıtım ve Tecrit', 'Yalıtım & İzolasyon', 34.50],
  ['BRSAN', 'Borusan Birleşik Boru Fabrikaları', 'Çelik Boru & Sanayi', 580.00],
  ['ERBOS', 'Erbosan Erciyas Boru Sanayii', 'Çelik Boru İmalat', 192.00],
  ['BMSCH', 'BMS Çelik Hasır Sanayi', 'Çelik Hasır & İnşaat', 22.40],
  ['TUCLK', 'Tuğçelik Alüminyum ve Metal', 'Alüminyum Enjeksiyon', 14.20],
  ['DMSAS', 'Demisaş Döküm Emaye Mamülleri', 'Otomotiv Döküm Parçaları', 10.80],
  ['SARKY', 'Sarkuysan Elektrolitik Bakır Sanayi', 'Bakır & Tel Sanayi', 34.20],
  ['CELHA', 'Çelik Halat ve Tel Sanayii', 'Çelik Halat & Sanayi', 42.00],
  ['PARSN', 'Parsan Ezme Çelik Dövme Sanayi', 'Otomotiv & Ağır Dövme', 124.00],
  ['JANTS', 'Jantsa Jant Sanayi ve Ticaret', 'Otomotiv Jant İmalat', 32.50],
  ['DITAS', 'Ditaş Doğan Yedek Parça', 'Otomotiv Direksiyon & Süspansiyon', 28.00],
  ['MAKTK', 'Makina Takım Endüstrisi', 'Kesici Takım & Makina', 8.90],
  ['KLMSN', 'Klimasan Klima Sanayi ve Ticaret', 'Ticari Soğutma Sistemleri', 28.40],
  ['EGSER', 'Ege Seramik Sanayi ve Ticaret', 'Seramik & Yapı Malzemeleri', 6.80],
  ['QUAGR', 'Qua Granite Hayal Yapı Ürünleri', 'Granit & Seramik', 3.40],
  ['BIENY', 'Bien Yapı Ürünleri Sanayi', 'Seramik & Banyo Ürünleri', 34.00],
  ['KMPUR', 'Kimteks Poliüretan Sanayi', 'Poliüretan Sistem Evi', 24.80],
  ['INVES', 'Investco Holding A.Ş.', 'Girişim Sermayesi & Finans', 340.00],
  ['GENIL', 'Gen İlaç ve Sağlık Ürünleri', 'İlaç & Biyoteknoloji', 78.50],
  ['TRILC', 'Türk İlaç ve Serum Sanayi', 'İlaç & Aşı Üretimi', 23.40],
  ['ONCSM', 'Oncosem Onkolojik Sistemler', 'Onkoloji & Medikal Cihaz', 186.00],
  ['RNPOL', 'Rainbow Polikarbonat Sanayi', 'Plastik Levha & Polikarbonat', 28.90],
  ['POLHO', 'Polisan Holding A.Ş.', 'Kimya, Boya & Liman', 14.80],
  ['DYOBY', 'Dyo Boya Fabrikaları Sanayi', 'Boya & Kimya', 42.50],
  ['MRSHL', 'Marshall Boya ve Vernik Sanayii', 'Boya Sanayi', 2140.00],
  ['DEVA', 'Deva Holding A.Ş.', 'İlaç Üretimi & Sağlık', 84.00],
  ['RTALB', 'RTA Laboratuvarları Biyolojik', 'Biyolojik Tanı & Sağlık', 14.20],
  ['ECZYT', 'Eczacıbaşı Yatırım Holding', 'Holding & Yatırım Ortaklığı', 275.00],
  ['ECILC', 'Eczacıbaşı İlaç Sınai ve Finansal', 'İlaç & Sağlık Yatırımları', 54.00],
  ['KARTN', 'Kartonsan Karton Sanayi ve Ticaret', 'Karton & Kağıt Ambalaj', 114.00],
  ['ALKIM', 'Alkim Alkali Kimya A.Ş.', 'Kimya & Madencilik', 32.80],
  ['ALKA', 'Alkim Kağıt Sanayi ve Ticaret', 'Kağıt Sanayii', 27.50],
  ['BAKAB', 'Bak Ambalaj Sanayi ve Ticaret', 'Esnek Ambalaj Sanayi', 48.00],
  ['GEDZA', 'Gediz Ambalaj Sanayi ve Ticaret', 'Oluklu Plastik Levha & Kutu', 38.40],
  ['PRKAB', 'Türk Prysmian Kablo ve Sistemleri', 'Enerji & Haberleşme Kabloları', 36.20],
  ['OZSUB', 'Özsu Balık Üretimi A.Ş.', 'Su Ürünleri Yetiştiriciliği', 24.50],
  ['SMRTG', 'Smart Güneş Enerjisi Teknolojileri', 'Güneş Paneli & EPC', 48.20],
  ['CVKMD', 'CVK Maden İşletmeleri Sanayi', 'Krom & Metal Madencilik', 460.00],
  ['KZBGY', 'Kuzugrup Gayrimenkul Yatırım', 'Gayrimenkul Yatırım Ortaklığı', 28.50],
  ['KZGYO', 'Kuzey Boru A.Ş.', 'Plastik Boru Sistemleri', 118.00],
  ['SURGY', 'Sur Tatil Evleri GYO', 'Turizm & Gayrimenkul GYO', 46.00],
  ['DMRGD', 'DMR Unlu Mamuller Üretim', 'Unlu Mamuller & Kafe', 16.80],
  ['BSOKE', 'Batısöke Söke Çimento Sanayii', 'Çimento & Klinker', 38.00],
  ['BASGZ', 'Başkent Doğalgaz Dağıtım GYO', 'Doğalgaz & Gayrimenkul', 19.50],
  ['BEYAZ', 'Beyaz Filo Oto Kiralama', 'Oto Filo Kiralama', 24.00],
  ['BVSAN', 'Bülbüloğlu Vinç Sanayi', 'Endüstriyel Vinç İmalat', 98.00],
  ['CEMAS', 'Çemaş Döküm Sanayi A.Ş.', 'Döküm & Taşlama Bilyası', 4.90],
  ['CMBTN', 'Çimbeton Hazırbeton ve Prefabrik', 'Hazır Beton & Prefabrik', 2650.00],
  ['CRFSA', 'CarrefourSA Carrefour Sabancı', 'Süpermarket & Perakende', 128.00],
  ['CUSAN', 'Çuhadaroğlu Metal Sanayi', 'Alüminyum Profil & Cephe', 22.00],
  ['DERHL', 'Derlüks Yatırım Holding', 'Deri, Konfeksiyon & Finans', 14.50],
  ['DNISI', 'Dinamik Isı Makina Yalıtım', 'Yalıtım & İzolasyon Ürünleri', 11.80],
  ['DOGUB', 'Doğusan Boru Sanayi ve Ticaret', 'Asbest & Çimento Boru', 12.40],
  ['DOCO', 'DO & CO Aktiengesellschaft', 'Gurme İkram & Otelcilik', 5940.00],
  ['EDATA', 'E-Data Teknoloji Pazarlama', 'Siber Güvenlik Dağıtımı', 21.60],
  ['EGGUB', 'Ege Gübre Sanayii A.Ş.', 'Gübre & Liman İşletmeciliği', 56.50],
  ['EGPRO', 'Ege Profil Ticaret ve Sanayi', 'PVC Profil & Pencere', 214.00],
  ['EMKEL', 'Emek Elektrik Endüstrisi', 'Yüksek Gerilim İmalatı', 38.50],
  ['EPLAS', 'Egeplast Ege Plastik Ticaret', 'Plastik Boru & Ek Parça', 9.80],
  ['ERSU', 'Ersu Meyve Suları Sarmaşık', 'Meyve Suyu Sanayi', 7.80],
  ['ESCAR', 'Escar Turizm Taşımacılık', 'Filo Kiralama & Ulaşım', 248.00],
  ['ETILR', 'Etiler Gıda ve Ticari Yatırımlar', 'Fast Food Restoran İşletmesi', 24.00],
  ['EYGYO', 'EYG Gayrimenkul Yatırım Ortaklığı', 'Gayrimenkul Projeleri', 8.90],
  ['FADE', 'Fade Gıda Yatırım Sanayi', 'Kurutulmuş Domates & Fide', 14.50],
  ['FMIZP', 'Federal-Mogul İzmit Piston', 'Piston & Motor Parçaları', 285.00],
  ['FORMT', 'Formet Metal ve Cam Sanayi', 'Metal Eşya & Çelik Kapı', 3.60],
  ['FRIGO', 'Frigo-Pak Gıda Maddeleri Sanayi', 'Narenciye Konservesi', 7.40],
  ['FZLGY', 'Fuzul Gayrimenkul Yatırım Ortaklığı', 'Konut Projeleri & GYO', 16.80],
  ['GEDIK', 'Gedik Yatırım Menkul Değerler', 'Aracı Kurum & Yatırım', 14.20],
  ['GENTS', 'Gentaş Dekoratif Yüzeyler', 'Laminat & Yapı Malzemeleri', 8.90],
  ['GEREL', 'Gersan Elektrik Ticaret ve Sanayi', 'Elektrik Busbar & Şarj İstasyonu', 32.00],
  ['GLBMD', 'Global Menkul Değerler', 'Menkul Kıymet Aracı Kurumu', 68.00],
  ['GLCVY', 'Gelecek Varlık Yönetimi', 'Varlık Yönetimi & Finans', 38.40],
  ['GLRYH', 'Güler Yatırım Holding', 'Yatırım Holding & Finans', 12.90],
  ['GLYHO', 'Global Yatırım Holding', 'Liman İşletmeciliği & Enerji', 14.60],
  ['GOZDE', 'Gözde Girişim Sermayesi Yatırım', 'Girişim Sermayesi Ortaklığı', 28.50],
  ['GSDDE', 'GSD Denizcilik Gayrimenkul', 'Kuru Yük Taşımacılığı & Denizcilik', 11.20],
  ['GSDHO', 'GSD Holding A.Ş.', 'Denizcilik, Bankacılık & Enerji', 4.40],
  ['GZNMI', 'Gezinomi Seyahat Turizm', 'Turizm & Online Seyahat', 48.00],
  ['HALKB', 'Türkiye Halk Bankası A.Ş.', 'Kamu Bankacılığı', 16.80],
  ['HATEK', 'Hateks Hatay Tekstil İşletmeleri', 'İplik & Havlu Dokuma Sanayi', 14.60],
  ['HDFGS', 'Hedef Girişim Sermayesi Yatırım', 'Girişim Sermayesi', 2.80],
  ['HEDEF', 'Hedef Holding A.Ş.', 'Finans, Teknoloji & Yatırım', 26.50],
  ['HUBVC', 'Hub Girişim Sermayesi Yatırım', 'Teknoloji Girişim Yatırımı', 8.40],
  ['ICBCT', 'ICBC Turkey Bank A.Ş.', 'Ticari Bankacılık', 12.60],
  ['IEYHO', 'Işıklar Enerji ve Yapı Holding', 'Kraft Torba & Enerji', 4.20],
  ['IHEVA', 'İhlas Ev Aletleri İmalat', 'Küçük Ev Aletleri Sanayi', 3.80],
  ['IHGZV', 'İhlas Gazetecilik A.Ş.', 'Medya & Baskı Hizmetleri', 3.40],
  ['IHLAS', 'İhlas Holding A.Ş.', 'Medya, İnşaat & Ticaret', 1.45],
  ['IHLGM', 'İhlas Gayrimenkul Proje', 'İnşaat & Gayrimenkul', 1.85],
  ['IHMAD', 'İhlas Madencilik Enerji', 'Maden Arama & İşletme', 11.20],
  ['IMASM', 'İmaş Makina Sanayi A.Ş.', 'Değirmen Makineleri İmalatı', 16.50],
  ['INFO', 'İnfo Yatırım Menkul Değerler', 'Aracı Kurum & Portföy Yönetimi', 13.80],
  ['ISBIR', 'İşbir Holding A.Ş.', 'Sentetik Dokuma & Sünger', 184.00],
  ['ISDMR', 'İskenderun Demir ve Çelik', 'Entegre Yassı Çelik Sanayi', 39.40],
  ['ISFIN', 'İş Finansal Kiralama A.Ş.', 'Finansal Kiralama (Leasing)', 14.20],
  ['ISGSY', 'İş Girişim Sermayesi Yatırım', 'Girişim Sermayesi Ortaklığı', 24.00],
  ['ISKPL', 'Işık Plastik Sanayi ve Dış Ticaret', 'Endüstriyel Plastik Levhalar', 8.80],
  ['ISMEN', 'İş Yatırım Menkul Değerler', 'Yatırım Bankacılığı & Aracı Kurum', 34.60],
  ['ISSEN', 'İşbir Sentetik Dokuma Sanayi', 'Teknik Tekstil & Ambalaj', 12.80],
  ['ISYAT', 'İş Yatırım Ortaklığı', 'Menkul Kıymet Yatırım Ortaklığı', 9.60],
  ['ITTFH', 'İttifak Holding (İmaş Grup)', 'İnşaat, Perakende & Makine', 3.60],
  ['IZMDC', 'İzmir Demir Çelik Sanayi', 'İnşaat Çeliği & Kütük Demir', 6.40],
  ['KAPLM', 'Kaplamin Ambalaj Sanayi', 'Oluklu Mukavva Kutu', 142.00],
  ['KARYA', 'Kartal Yenilenebilir Enerji', 'Güneş Enerjisi Santralleri', 28.00],
  ['KATMR', 'Katmerciler Araç Üstü Ekipman', 'Zırhlı Savunma Araçları', 2.45],
  ['KCAER', 'Kocaer Çelik Sanayi ve Ticaret', 'Çelik Profil & Yapısal Çelik', 48.00],
  ['KERVT', 'Kerevitaş Gıda Sanayi (SuperFresh)', 'Dondurulmuş Gıda & Yağ', 14.80],
  ['KIMMR', 'Ersin Kim Market Mağazacılık', 'Süpermarket Zinciri', 8.20],
  ['KLNMA', 'Türkiye Kalkınma ve Yatırım Bankası', 'Yatırım & Kalkınma Bankası', 34.00],
  ['KLRHO', 'Kiler Holding A.Ş.', 'İnşaat, Enerji & Perakende', 38.00],
  ['KNFRT', 'Konfrut Tarım A.Ş.', 'Meyve Konsantresi & Tarım', 11.40],
  ['KONKA', 'Konya Kağıt Sanayi ve Ticaret', 'Yazı Tabı Kağıdı & Defter', 49.00],
  ['KONYA', 'Konya Çimento Sanayii', 'Çimento Sanayi', 11200.00],
  ['KORDS', 'Kordsa Teknik Tekstil', 'Lastik Güçlendirme & Kompozit', 94.00],
  ['KRGYO', 'Körfez Gayrimenkul Yatırım', 'Gayrimenkul Projeleri', 28.00],
  ['KRPLS', 'Koroplast Temizlik Ambalaj', 'Çöp Torbası & Mutfak Yardımcı', 9.20],
  ['KRSTL', 'Kristal Kola ve Meşrubat Sanayi', 'Gazlı İçecek & Meyve Suyu', 9.80],
  ['KRTEK', 'Karsu Tekstil Sanayii', 'Modal & Karışımlı İplik', 24.00],
  ['KRVGD', 'Kervan Gıda Sanayi (Bebeto)', 'Yumuşak Şekerleme Üretimi', 2.65],
  ['KSTUR', 'Kuştur Kuşadası Turizm Endüstri', 'Tatil Köyü & Otelcilik', 5600.00],
  ['KTLEV', 'Katılımevim Tasarruf Finansman', 'Faizsiz Tasarruf Finansman', 68.00],
  ['KTSKR', 'Kütahya Şeker Fabrikası', 'Şeker & Tarımsal Ürünler', 58.00],
  ['KUTPO', 'Kütahya Porselen Sanayi', 'Porselen Sofra Eşyası', 74.00],
  ['KUVVA', 'Kuvva Gıda Ticaret', 'Gıda & Ticaret', 46.00],
  ['KUYAS', 'Kuvva Kuyumcukent Gayrimenkul', 'Ticari Gayrimenkul Geliştirme', 54.00],
  ['LIDER', 'Lider Filo Otomobil Kiralama', 'Uzun Dönemli Filo Kiralama', 68.00],
  ['LILAK', 'Lila Kağıt Sanayi ve Ticaret', 'Temizlik Kağıtları Sanayi', 26.50],
  ['LKMNH', 'Lokman Hekim Engürüsağ Sağlık', 'Özel Hastanecilik Hizmetleri', 18.20],
  ['LUKSK', 'Lüks Kadife Ticaret ve Sanayi', 'Döşemelik Kadife Dokuma', 68.00],
  ['MAALT', 'Marmaris Altınyunus Turistik Tesis', 'Otelcilik & Turizm', 980.00],
  ['MACKO', 'Maçkolik İnternet Hizmetleri', 'Spor Medyası & Canlı Skor', 94.00],
  ['MAKIM', 'Makim Makina Teknolojileri', 'Hassas Döküm & Güvenlik Turnike', 42.00],
  ['MARBL', 'Tureks Turunç Madencilik', 'Mermer & Doğaltaş İhracatı', 14.80],
  ['MARKA', 'Marka Yatırım Holding', 'Yatırım Holding', 84.00],
  ['MARTI', 'Martı Otel İşletmeleri', 'Otelcilik & Tatil Köyü', 4.80],
  ['MEDTR', 'Meditera Tıbbi Malzeme Sanayi', 'Tıbbi Cihaz & Serum Seti', 38.00],
  ['MEGAP', 'Mega Polietilen Köpük Sanayi', 'Polietilen Sünger & Tekstil', 4.90],
  ['MEGSP', 'Mega Metal Sanayi ve Ticaret', 'Süper İnce Bakır Tel', 42.00],
  ['MENGD', 'MNG Havayolları Kargo Ulaşım', 'Hava Kargo Taşımacılığı', 86.00],
  ['MERCN', 'Mercan Kimya Sanayi ve Ticaret', 'Parafin & Kimyasal Emülsiyon', 12.80],
  ['MERIT', 'Merit Turizm Yatırımları', 'Lüks Otel Zinciri', 128.00],
  ['MERKO', 'Merko Gıda Sanayi ve Ticaret', 'Sanayi Tipi Domates Salçası', 9.40],
  ['METRO', 'Metro Ticari ve Mali Yatırımlar', 'Yolcu Ulaşımı & Turizm', 2.80],
  ['METUR', 'Metemtur Otelcilik ve Turizm', 'Turizm & Gayrimenkul', 14.20],
  ['MHRGY', 'MHR Gayrimenkul Yatırım', 'Ticari Ofis & GYO', 4.90],
  ['MNDRS', 'Menderes Tekstil Sanayi', 'Ev Tekstili & Nevresim', 9.80],
  ['MNDTR', 'Mondi Turkey Oluklu Mukavva', 'Ambalaj & Kutu Üretimi', 16.50],
  ['MOGAN', 'Mogan Enerji Yatırım Holding', 'Rüzgar & Jeotermal Enerji', 12.80],
  ['MPARK', 'MLP Sağlık Hizmetleri (Medical Park)', 'Özel Hastane Zinciri', 342.00],
  ['MRGYO', 'Martı Gayrimenkul Yatırım', 'Turizm Odaklı GYO', 7.40],
  ['MSGYO', 'Mistral Gayrimenkul Yatırım', 'Ofis & Yaşam Merkezi', 8.20],
  ['MTRKS', 'Matriks Bilgi Dağıtım Hizmetleri', 'Finansal Veri Terminali', 54.00],
  ['MTRYO', 'Metro Yatırım Ortaklığı', 'Portföy Yönetimi', 7.80],
  ['NIBAS', 'Niğde Beton Sanayi ve Ticaret', 'Prefabrik Beton Elemanları', 18.50],
  ['NTHOL', 'Net Holding A.Ş.', 'Otelcilik, Şans Oyunları & Turizm', 46.00],
  ['NUGYO', 'Nurol Gayrimenkul Yatırım', 'Lüks Konut & Plaza GYO', 4.80],
  ['OASIS', 'Oasis Rezidans Gayrimenkul', 'Gayrimenkul Yatırım Ortaklığı', 14.50],
  ['OFSYM', 'Ofis Yem Gıda Sanayi', 'Karma Hayvan Yemi İmalatı', 48.00],
  ['ORGE', 'Orge Enerji Elektrik Taahhüt', 'Metro & Tünel Elektrik Taahhüt', 78.00],
  ['ORMA', 'Orma Orman Mamulleri İntegre', 'Yonga Levha & Melamin Kaplama', 168.00],
  ['OSMEN', 'Osmanlı Yatırım Menkul Değerler', 'Online Menkul Değerler', 186.00],
  ['OSTIM', 'Ostim Endüstriyel Yatırımlar', 'Sanayi Sitesi & Gayrimenkul', 8.40],
  ['OYAYO', 'Oyak Yatırım Ortaklığı', 'Portföy Yatırımı', 34.00],
  ['OYLUM', 'Oylum Sınai Yatırımlar', 'Bisküvi, Gofret & Şekerleme', 9.20],
  ['OYYAT', 'Oyak Yatırım Menkul Değerler', 'Yatırım Bankacılığı', 48.00],
  ['OZGYO', 'Özderici Gayrimenkul Yatırım', 'Gayrimenkul Geliştirme', 5.60],
  ['OZRDN', 'Özerden Plastik Sanayi', 'Balonlu Naylon Ambalaj', 38.00],
  ['PAGYO', 'Panora Gayrimenkul Yatırım', 'Alışveriş Merkezi İşletmeciliği', 44.00],
  ['PANVE', 'Panelsan Çatı Cephe Sistemleri', 'Sandviç Panel İmalatı', 68.00],
  ['PASTV', 'Pasifik Teknoloji Sanayi', 'Yazılım, Siber Güvenlik & Drone', 74.00],
  ['PCILT', 'PC İletişim Medya Sistemleri', 'Medya Planlama & Satın Alma', 16.80],
  ['PEGYO', 'Pera Gayrimenkul Yatırım', 'Tarihi Yapı & GYO', 8.40],
  ['PEKGY', 'Peker Gayrimenkul Yatırım', 'Yurtdışı Gayrimenkul Projeleri', 28.00],
  ['PENGD', 'Penguen Gıda Sanayi A.Ş.', 'Sebze Konservesi & Reçel', 7.40],
  ['PENTA', 'Penta Teknoloji Ürünleri Dağıtım', 'Bilişim & Yazılım Distribütörü', 14.80],
  ['PKENT', 'Petrokent Turizm A.Ş.', 'Tatil Köyü & Devremülk', 198.00],
  ['PLTUR', 'Platform Turizm Taşımacılık', 'Personel & Yolcu Taşımacılığı', 16.50],
  ['PNLSN', 'Panel Sistemleri Çatı Cephe', 'Yalıtımlı Panel Üretimi', 58.00],
  ['POLTK', 'Politeknik Metal Sanayi', 'Alüminyum Yüzey İşlem Kimyasalları', 14200.00],
  ['PRDGS', 'Pardus Girişim Sermayesi', 'Girişim Sermayesi Yatırımları', 6.80],
  ['PRKME', 'Park Elektrik Üretim Madencilik', 'Maden & Enerji Yatırımları', 24.50],
  ['PRZMA', 'Prizma Pres Matbaacılık', 'Matbaacılık & Etiket', 38.00],
  ['PSDTC', 'Pasifik Donanım ve Yazılım', 'Bilişim Çözümleri', 64.00],
  ['PSGYO', 'Pasifik Gayrimenkul Yatırım Ortaklığı', 'Next Level Konut & Ofis GYO', 7.90],
  ['QNBFB', 'QNB Finansbank A.Ş.', 'Özel Bankacılık Hizmetleri', 285.00],
  ['QNBFL', 'QNB Finans Finansal Kiralama', 'Leasing Çözümleri', 142.00],
  ['RALYH', 'Ral Yatırım Holding A.Ş.', 'İnşaat, Taahhüt & Yenilenebilir Enerji', 184.00],
  ['RAYSG', 'Ray Sigorta A.Ş.', 'Elementer Sigortacılık', 380.00],
  ['RODRF', 'Rodrigo Tekstil Sanayi', 'Jean & Hazır Giyim', 84.00],
  ['ROYAL', 'Royal Halı İplik Tekstil', 'Makine Halısı & İplik', 16.50],
  ['RUBNS', 'Rubenis Tekstil Sanayi', 'İplik Dokuma & Kumaş', 34.00],
  ['RUZGR', 'Rönesans Gayrimenkul Yatırım', 'AVM & Ticari Gayrimenkul', 138.00],
  ['RYGYO', 'Reysaş Gayrimenkul Yatırım', 'Lojistik Depolama GYO', 42.00],
  ['RYSAS', 'Reysaş Taşımacılık ve Lojistik', 'Entegre Lojistik & Depolama', 48.00],
  ['SAFKR', 'Safkar Ege Soğutmacılık', 'Raylı Sistemler & Otobüs Kliması', 46.00],
  ['SAMAT', 'Saray Matbaacılık Kağıtçılık', 'Ambalaj & Matbaa', 42.00],
  ['SANEL', 'San-El Mühendislik Elektrik', 'Elektrik Panoları İmalatı', 24.00],
  ['SANFM', 'Sanifoam Sünger Sanayi', 'Akustik & Teknik Sünger', 28.00],
  ['SANKO', 'Sanko Pazarlama İthalat İhracat', 'Tekstil & İplik Pazarlama', 36.00],
  ['SEKFK', 'Şeker Finansal Kiralama', 'Kobi Leasing Hizmetleri', 16.80],
  ['SEKUR', 'Sekuro Plastik Ambalaj Sanayi', 'Streç Film & Balonlu Torba', 14.50],
  ['SELGD', 'Selçuk Gıda Endüstri İhracat', 'Kurutulmuş İncir & Meyve', 26.00],
  ['SEYKM', 'Seyitler Kimya Sanayi', 'Tıbbi Flaster & İlk Yardım', 9.80],
  ['SILVR', 'Silverline Endüstri ve Ticaret', 'Ankastre Mutfak Cihazları', 18.20],
  ['SKTAS', 'Söktaş Tekstil Sanayi', 'Gömleklik Lüks Kumaş', 4.80],
  ['SKYMD', 'Şeker Yatırım Menkul Değerler', 'Aracı Kurum Hizmetleri', 11.40],
  ['SNDUR', 'Sanica Isı Sanayi A.Ş.', 'Panel Radyatör & Kombi', 32.00],
  ['SNICA', 'Sanica Isı Sanayi A.Ş.', 'Isıtma Sistemleri & Boru', 6.80],
  ['SNKRN', 'Senkron Siber Güvenlik Yazılım', 'Siber Güvenlik Entegratörü', 38.00],
  ['SOKE', 'Söke Değirmencilik Sanayi', 'Paketli Un & Bakliyat', 13.80],
  ['SONME', 'Sönmez Filament Sentetik İplik', 'Sentetik İplik Sanayi', 74.00],
  ['SRVGY', 'Servet Gayrimenkul Yatırım', 'Ticari Gayrimenkul Portföyü', 480.00],
  ['SUMAS', 'Sumaş Saraylı Mdf Sanayi', 'MDF & Sunta İmalatı', 490.00],
  ['SUNTK', 'Sun Tekstil Sanayi ve Ticaret', 'Hazır Giyim Tasarım & İhracat', 18.60],
  ['SUWEN', 'Suwen Tekstil Sanayi ve Pazarlama', 'İç Giyim & Ev Giyimi Zinciri', 21.00],
  ['TARKM', 'Tarkim Bitki Koruma Sanayi', 'Zirai İlaç & Bitki Koruma', 580.00],
  ['TATEN', 'Tatlıpınar Enerji Üretim', 'Rüzgar & Hibrit GES Santralleri', 28.50],
  ['TDGYO', 'Trend Gayrimenkul Yatırım', 'Konut Projeleri', 14.20],
  ['TEKTU', 'Tek-Art Turizm Zigana Tesisleri', 'Otel & Tatil Köyü', 3.80],
  ['TERA', 'Tera Yatırım Menkul Değerler', 'Kurumsal Finansman & Aracılık', 38.00],
  ['TEZOL', 'Europap Tezol Kağıt Sanayi', 'Temizlik Kağıdı İmalatı', 16.40],
  ['TGSAS', 'TGS Dış Ticaret A.Ş.', 'Sektörel Dış Ticaret Şirketi', 26.00],
  ['TKFEN', 'Tekfen Holding A.Ş.', 'Müteahhitlik, Gübre & Tarım', 74.00],
  ['TKNSA', 'Teknosa İç ve Dış Ticaret', 'Tüketici Elektroniği Perakende', 34.00],
  ['TLMAN', 'Trabzon Liman İşletmeciliği', 'Liman Yükleme & Depolama', 114.00],
  ['TNZTP', 'Tapdi Oksijen Özel Sağlık', 'Tınaztepe Özel Hastaneleri', 8.20],
  ['TRCAS', 'Turcas Petrol A.Ş.', 'Akaryakıt Dağıtım & Enerji', 24.50],
  ['TSPOR', 'Trabzonspor Sportif Yatırım', 'Futbol Kulübü & Sportif Hizmet', 1.85],
  ['TTRAK', 'Türk Traktör ve Ziraat Makineleri', 'Traktör & Ziraat Ekipmanları', 780.00],
  ['TUREX', 'Tureks Turizm Taşımacılık', 'Toplu Taşıma & Personel Servisi', 46.00],
  ['TURGG', 'Türker Proje Gayrimenkul', 'Arazi Geliştirme Projeleri', 780.00],
  ['UFUK', 'Ufuk Yatırım Yönetim ve Gayrimenkul', 'Girişim & Finansal Yatırım', 184.00],
  ['ULUFA', 'Ulusal Faktoring A.Ş.', 'Tedarikçi Finansmanı & Faktoring', 11.20],
  ['ULUSE', 'Ulusoy Elektrik İmalat Taahhüt', 'Orta Gerilim Ekipmanları', 194.00],
  ['UNLU', 'Ünlü Yatırım Holding', 'Yatırım Bankacılığı & Aracılık', 16.80],
  ['VAKBN', 'Türkiye Vakıflar Bankası T.A.O.', 'Kamu Bankacılığı Hizmetleri', 21.40],
  ['VAKFN', 'Vakıf Finansal Kiralama', 'Ekipman Finansal Kiralama', 4.80],
  ['VANGD', 'Vanet Gıda Sanayi İç ve Dış Ticaret', 'Et & Şarküteri Ürünleri', 28.00],
  ['VERTU', 'Verusaturk Girişim Sermayesi', 'Girişim Sermayesi Portföyü', 48.00],
  ['VERUS', 'Verusa Holding A.Ş.', 'Maden, Enerji & Teknoloji Yatırımı', 315.00],
  ['VKFYO', 'Vakıf Menkul Kıymet Yatırım', 'Menkul Kıymet Portföyü', 26.00],
  ['VKGYO', 'Vakıf Gayrimenkul Yatırım Ortaklığı', 'Finans Merkezi Konut & Ofis GYO', 2.40],
  ['VKING', 'Viking Kağıt ve Selüloz Sanayi', 'Temizlik Kağıdı & Selüloz', 36.00],
  ['YAPRK', 'Yaprak Süt ve Besi Çiftlikleri', 'Süt Sığırcılığı & Çiğ Süt Üretimi', 74.00],
  ['YAYLA', 'Yayla Enerji Üretim Turizm', 'Yenilenebilir Enerji & İnşaat', 18.40],
  ['YGGYO', 'Yeni Gimat Gayrimenkul Yatırım Ortaklığı', 'Ankamall AVM & Otel GYO', 48.00],
  ['YGYO', 'Yeşil Gayrimenkul Yatırım Ortaklığı', 'Toplu Konut & Yaşam Merkezi', 8.20],
  ['YONGA', 'Yonga Mobilya Sanayi ve Ticaret', 'Masif Mobilya İhracatı', 68.00],
  ['YUNSA', 'Yünlü Sanayi ve Ticaret (Yünsa)', 'Kamgarn Yünlü Dokuma Kumaş', 64.00],
  ['YYAPI', 'Yeşil Yapı Endüstrisi', 'Altyapı & Konut İnşaatı', 4.90],
  ['ZEDUR', 'Zedur Enerji Elektrik Üretim', 'Güneş & Hidroelektrik Santralleri', 14.80],
  ['ZRGYO', 'Ziraat Gayrimenkul Yatırım Ortaklığı', 'İstanbul Finans Merkezi Kule GYO', 6.40]
];

// Deduplicate BIST items by symbol
const uniqueBistMap = new Map();
bistListRaw.forEach(([symbol, name, sector, basePrice]) => {
  if (!uniqueBistMap.has(symbol)) {
    uniqueBistMap.set(symbol, {
      symbol,
      name,
      exchange: 'BIST',
      category: 'BIST',
      currency: '₺',
      yahooTicker: `${symbol}.IS`,
      sector,
      basePrice
    });
  }
});

const bistList = Array.from(uniqueBistMap.values());
console.log('BIST Universe count:', bistList.length);

const bistFileContent = `export interface StockDefinition {
  symbol: string;
  name: string;
  exchange: string;
  category: 'BIST';
  currency: '₺';
  yahooTicker: string;
  sector: string;
  basePrice: number;
}

// BIST Tüm / BIST 100 / BIST 300 En Likit ve Popüler 300+ Hisse Senedi
export const BIST_300_STOCKS: StockDefinition[] = ${JSON.stringify(bistList, null, 2)};
`;

fs.writeFileSync('./server/data/bistUniverse.ts', bistFileContent, 'utf8');
console.log('Successfully wrote server/data/bistUniverse.ts with', bistList.length, 'stocks.');
